### ISSUE TITLE
OpenSMILE missing from VM

### ISSUE THREAD

**Issue by orasanen** [srvk/DiViMe#104]
SMILEextract is no longer working after rebuilding the VM, wget of OpenSMILE toolbox during installation is apparently empty (issue replicated by Marvin). This causes problems with all tools that use OpenSMILE feature extraction frontend.

**Comment by MarvinLavechin** [comment]
The old link appeared to be broken : 

`https://www.audeering.com/download/1318`

Replaced by : 

`https://www.audeering.com/download/opensmile-2-3-0-tar-gz/?wpdmdl=4782`

Waiting to build a new VM and check that everything is OK before pushing on major_reorganization

**Comment by MarvinLavechin** [comment]
You're definitely right, my bad !
