### ISSUE TITLE
WCE missing from the latest version

### ISSUE THREAD

**Issue by orasanen** [srvk/DiViMe#105]
WCE repo and its installation steps are missing from the bootstrap.sh after merging reorganization branch to the main branch.

**Comment by MarvinLavechin** [comment]
This part of the code didn't survive to the merge with the **origin/yunified** branch ([here](https://github.com/srvk/DiViMe/commit/9386e34a6387c0be8f0c97f67c9378c543a818e0)). I'm not sure why, but it seems that Git identified this portion of the code as being outdated (therefore, replacing it by the **origin/yunified** version of **bootstrap.sh**).

I'm just waiting to rebuild a VM and launch the tests before pushing and closing the issue.

**Comment by MarvinLavechin** [comment]
Ok !
Now that it has been pushed on the **master** branch, it shouldn't be deleted by any merge.
