### ISSUE TITLE
eaf2enriched_txt.sh (eaf2txt.py more specifically) fails to write out all content, crashes to unicode error

### ISSUE THREAD

**Issue by orasanen** [srvk/DiViMe#106]
Using the latest version of the VM, I get the following unicode error when running eaf2enriched_txt.sh (see below). As a result, only a small subset of all transcripts in the .eaf file end up in the enriched txt file. 

-----
Directory found.
Converting data/eafs//1499.eaf files to data/eafs//1499.txt ...
Parsing unknown version of ELAN spec... This could result in errors...
Traceback (most recent call last):
  File "/home/vagrant/utils/eaf2txt.py", line 95, in <module>
    main()
  File "/home/vagrant/utils/eaf2txt.py", line 87, in main
    eaf2txt(args.input, output)
  File "/home/vagrant/utils/eaf2txt.py", line 58, in eaf2txt
    output_file.write("%d\t%d\t%s\t%s\t%s\n" % (onset, offset, receiver, transcript, speaker))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 30: ordinal not in range(128)
Enriching data/eafs//1499.txt
Cleaning data/eafs//1499.txt
Pĥonemizing /vagrant/data/eafs/clean_transcript.txt3.tmp ...
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/vagrant/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Done.
-----

**Comment by MarvinLavechin** [comment]
Solved by setting the default encoding to utf8
