### ISSUE TITLE
References Missing

### ISSUE THREAD

**Issue by jukaradayi** [srvk/DiViMe#11]
References are missing for OpenSmile and To Combo SAD.

**Comment by alecristia** [comment]
The solution is to add the corresponding sections in the README file, making sure to mention the sources. For to combo sad the citation is:
A. Ziaei, A. Sangwan, J.H.L. Hansen, "Effective word count estimation for long duration daily naturalistic audio recordings," Speech Communication, vol. 84, pp. 15-23, Nov. 2016.

**Comment by orasanen** [comment]
"[1] S.O. Sadjadi, J.H.L. Hansen, "Unsupervised Speech Activity Detection using Voicing Measures and Perceptual Spectral Flux," IEEE Signal Processing Letters, vol. 20, no. 3, pp. 197-200, March 2013 " is still missing. TO-Combo-SAD should cite both papers (Ziaei & Hansen, 2016) and this one.
