### ISSUE TITLE
Yunitator error: can't find lapack

### ISSUE THREAD

**Issue by riebling** [srvk/DiViMe#110]
```
Traceback (most recent call last):
  File "yunified.py", line 83, in <module>
    net = Net(50, 200, 4) #.cuda()
  File "/home/vagrant/repos/Yunitator/Yunitator/Net.py", line 13, in __init__
    nn.init.orthogonal_(self.gru.weight_ih_l0); nn.init.constant_(self.gru.bias_ih_l0, 0)
  File "/home/vagrant/anaconda/envs/divime/lib/python3.6/site-packages/torch/nn/init.py", line 356, in orthogonal_
    q, r = torch.qr(flattened)
RuntimeError: geqrf: Lapack library not found in compile time
 at /tmp/pip-req-build-v47_5uey/aten/src/TH/generic/THLapack.cpp:237
```
and yet the system-wide lapack library is installed. Did something go wrong during install of Torch?
Interesting in the error message it looks like running Python 3.6. Did the installation of Torch at provisioning time apply to a different python virtualenv than the one that runs Python 3.6? 

I wonder if the Python3 divime anaconda virtualenv is the one where torch gets installed?
I see that noisemesSad.sh and yunitate.sh both use this virtualenv.

**Comment by riebling** [comment]
(because of this, VCM fails test later on:
```
Error: Cannot find corresponding SAD outputs. Please run yunicatator first!
/home/vagrant/launcher/vcm.sh finished running
```
)

**Comment by riebling** [comment]
It looks like there might be a solution: though it makes no sense why an environment.yml that specifies python packages, versions, and dependencies - should produce different results, it apparently does. So our system uses Python 3 defined by this conf/environment.yml to install pytorch-cpu which gets the above error. But if we ask for a newer Python version, and a specific (also newer) pytorch-cpy version, things run without complaint.

Also helps clear out: we don't need to install torch and cuda python modules for both python 2 and python 3 if only needed by the tools that require python 3 (Yunitator and ??)- can remove the lines that install them python 2, saving a tiny bit of time during 'vagrant up' provisioning.

**Comment by riebling** [comment]
Darn. VCM needs torch, so we need to install both python2 and python3 versions.
-or- we can fix VCM to use the python3 installation of Torch... tried it, it works :)

**Comment by MarvinLvn** [comment]
I got the same error despite the fact that your bugfix is still there.
I tried to fix this issue for several hours now :/ Might need a hand !

**Comment by MarvinLvn** [comment]
I couldn't find out what went wrong during the Lapack installation step.
I fixed this bug by removing the part of the code that was producing the error. (It was for layers initialization, which was useless since we load the model with a .pkl)

**Comment by GladB** [comment]
I just got this error when trying to use `high_volubility.py` with Yunitator, for both `yunitator-english` and `yunitator-universal` versions. Does this bug have a definitive fix that I missed?

**Comment by alecristia** [comment]
do you still get output? that is, could it be an error message with no consequences?

**Comment by GladB** [comment]
I believe not.  The context is the following: I am trying to use the high_volubility.py script, and it does not get past the yunitator step, so I run:

```python utils/high_volubility.py /vagrant/data/BER/full/0396.wav --diar yunitator_english --mode CHI --nb_chunks 5```

and the output is

```Traceback (most recent call last):
  File "yunified.py", line 100, in <module>
    net = Net(150, 200, 4)
  File "/home/vagrant/repos/Yunitator/Yunitator/Net.py", line 13, in __init__
    nn.init.orthogonal_(self.gru.weight_ih_l0); nn.init.constant_(self.gru.bias_ih_l0, 0)
  File "/home/vagrant/anaconda/envs/divime/lib/python3.6/site-packages/torch/nn/init.py", line 356, in orthogonal_
    q, r = torch.qr(flattened)
RuntimeError: geqrf: Lapack library not found in compile time
 at /tmp/pip-req-build-3sb4rz3f/aten/src/TH/generic/THLapack.cpp:237
ls: cannot access /vagrant/tmp/Yunitemp/*.rttm.sorted: No such file or directory
/home/vagrant/launcher/yunitate.sh finished running
ls: cannot access /vagrant/tmp/Yunitemp/*.rttm: No such file or directory
Traceback (most recent call last):
  File "utils/high_volubility.py", line 593, in <module>
    main()
  File "utils/high_volubility.py", line 561, in main
    sorted_files = read_analyses(temp_abs, args.sad, nb_chunks*3, args.diar, args.mode)
  File "utils/high_volubility.py", line 342, in read_analyses
    "to increase the size of the chunks.")
ValueError: No moments for the {} mode has been found.
 Try to decrease the step parameter or to increase the size of the chunks.```

**Comment by MarvinLvn** [comment]
Weird. The exact same command (on the exact same file) runs well on my computer.
When was the last time you build the VM from scratch ?

Can you try the following : 

```
cd repos
rm -rf Yunitator
git clone https://github.com/srvk/Yunitator
```

And let me know what happens ?

**Comment by MarvinLvn** [comment]
I do think the Lapack problem has been fixed by https://github.com/srvk/Yunitator/commit/306d9e9febe6aea4df5aaf6913dbd6ceb50bc31d

**Comment by GladB** [comment]
I thought I had the latest version since `high_volubility.py` was the right one, but indeed pulling the latest version of Yunitator solved the issue, thanks!
