### ISSUE TITLE
high_volubility.py hard-coded paths

### ISSUE THREAD

**Issue by GladB** [srvk/DiViMe#114]
It looks like the hard-coded paths in utils/high_volubility.py are not up to date anymore, eg line 135, 137 and 141 with `tools/` instead of `utils/`

``` cmd = ['tools/{}.sh'.format(diar), '{}'.format(temp_rel)] ```

edit: actually the tools that are used here were moved to `launcher/`, so it would mean replace `tools/`by `launcher/`

**Comment by MarvinLvn** [comment]
Thanks Gladys ! Indeed, this scripts needs an update !
