### ISSUE TITLE
high_volubility.py percentage vs count of extracted chunks

### ISSUE THREAD

**Issue by GladB** [srvk/DiViMe#115]
Is there a reason why the script extracts a number of 5 minutes chunks based on a % and not a count? Would it be possible to implement a count argument (mutually exclusive with the percentage argument)?

**Comment by MarvinLvn** [comment]
Well, I'm not sure it's really useful to allow the user both to use count and %.
But now that you're pointing out that, I'd definitely go for the count solution rather than the % one which seems less convenient.

**Comment by MarvinLvn** [comment]
I've been talking too fast. Let's start from scratch and suppose we have a daylong recording. The script does the following : 

1) Extract 10 seconds chunks (uniformly distributed) and feed them to a SAD or diarization tool. Let's suppose that we have N chunks.
2) Keep 10% of them (the ones that contain the most speech) and extend them to get 2 minutes around the initial 10 seconds chunks. Therefore, we have N/10 chunks of 2 minutes.
3) Rerun these N/10 chunks, keep 10% of them and extend them to finally get N/100 chunks of 5 minutes.

The %-based parameter seems intuitive here. If you want to rely on counts, you should provide two numbers (for each filtering steps)

**Comment by GladB** [comment]
I guess the one advantage that I am looking for is to specify how many 5-minutes chunks the script will output, which is not straightforward with %. I would also like to have the same number of chunks whether the file is 16 hours long or 10 hours long (as in *get the 40 5-minutes chunks with the most speech*; if the file is 200 minutes long, then that means get all 5-minutes chunks)

I do not know how this would work with the way the script currently computes what it keeps or not, but giving two count values as argument would definitely be a solution. If that is not something that other people would find useful, I can implement it locally, I was just wondering if there was another reason for the %.

**Comment by MarvinLvn** [comment]
Your point about having the same number of files makes sense. It's definitely something I can implement in the coming days

**Comment by GladB** [comment]
Great! Something that I think would also be useful would be to indicate the rank of the chunk in its name in the output. By rank, I mean the index it would have in a sorted list, from chunk containing the most speech to chunk containing the least speech. For now, the name only contains the onset and offset of the chunk in the full file.

**Comment by MarvinLvn** [comment]
I keep that in mind ! Thanks for your feedback :) I'll keep you in touch

**Comment by GladB** [comment]
Alright, thanks!

**Comment by alecristia** [comment]
I'll add one more suggestion: Since the current implementation by the data folks involves their possibility to discard a chunk if it's "bad" in some way, then the system should return a list of clips, ranked, and with information of how much baby speech etc it had.

In fact, I think you had already implemented things to get a txt file with this information, right, Marvin?

**Comment by MarvinLvn** [comment]
Update : 

**high_volublity.py** takes the desired number of chunks as an input now.
Call example : 
```
python utils/high_volubility.py data/daylong/whole/0396.wav --diar yunitator_universal --mode CHI --nb_chunks 3
```

I completely got rid of the **percentage** parameter which didn't bring that much information and was not easy to use.

Now the script returns both the chunk (.wav format) and the output of the model that has been used.
Following Alex's suggestion, it also returns a .txt file summarizing the metrics of interest at the chunk level : 

```
filename,CHI_duration,MAL_duration,FEM_duration,ADU_ADU_turntaking,ADU_CHI_turntaking
yunitator_universal_0396_28685.0_28985.0,98.8,34.7,142.1,38,61
yunitator_universal_0396_16685.0_16985.0,96.9,26.8,56.9,15,17
yunitator_universal_0396_5285.0_5585.0,84.9,32.3,79.3,14,35
```

Where : 
+ ADU_ADU_turntaking is the number of turn-takings between 2 adults.
+ And ADU_CHI_turntaking is the number of turn-takings between a child and an adult.

Note that a turn-taking is considered as it is when two speakers of interest are speaking in a row. (Silence between the 2 speakers lower than 2 sec)

I haven't changed the naming convention of the extracted chunks. I could if Gladys thinks it's necessary (but the information is already in the .txt file)
