### ISSUE TITLE
Find high volubility sections

### ISSUE THREAD

**Issue by jukaradayi** [srvk/DiViMe#12]
Goal is to find areas of daylong recordings (about 10h long) that have a lot of speech -- that is, we want to find a time when there is a lot of talking out of the whole long recording. 
One implementation:

- [x]   extract short snippets (perhaps 10-s long) every some longer stretches (perhaps every 10-minutes)
- [x] run those snippets through noisemes
- [x] select top 10% snippets that have the most frames with speech
- [x] extract 2 minutes centered around those snippets
- [x] run those extended snippets through noisemes
- [x] find the top 10% 2-minute files that have the most frames with speech
- [x] extract 5 minute extended clips from the preceding selection: 2-minutes preceding + the 2 minute files that won in the immediately preceding step + 1 minute

**Comment by jukaradayi** [comment]
For the first step, should we take the first snippet at the 10 minute onset ? This would avoid the begining of the wav where the mic is prepared etc... which can be a part that contains speech but also very noisy, I don't know if we want to risk having it or not ?

**Comment by alecristia** [comment]
I think we can leave that in, because different people may have different rhythms. (I'd skip the first hour, perhaps someone else would only skip 30 minutes.)

**Comment by jukaradayi** [comment]
How do you think the user should use this feature ? 

By default, I included it in the tools/ folder in the VM (alongside the diartk, noisemes, etc.. tools), and built it so that it treats one daylong recording at a time, by mimicking the use of the other tools, i.e. `./high_volubility.py data/0396.wav' 
notice that since it treats one recording at a time, the command is more precise than the other tools. I could remove that precision and just treat all the recording in data/ , and it would be the same call as the other tools.
I also included some optionnal parameters with default values:
-the step between each snippet can be changed, by default it's 10 minutes ; 
-the size of the snippets can be changed, by default it's [10s, 2 minutes, 5minutes];  
-the path to the temporary folder used to store the [10s, 2minutes] long snippets can be changed, by default it's tmp;  
-the SAD tool to be used in the VM can be changed, by default it's noisemes_sad.

Again, to mimick the other tools, the outputs are the 5 minutes long chunks of audio, stored in the same folder as the daylong recording that's being analyzed, with the following convention for their name: 
`id_onset_offset.wav`
where id is the name of the daylong recording, and  [onset, offset] are the timestamps in seconds, written with 6 digits (e.g. 000120_000420), that indicate where the chunk was taken from in the original recording. 

When you validate/change these points we can close the issue !

**Comment by jukaradayi** [comment]
I'm adding to the list of optional parameters the percentage of snippets we want to keep. 

With the default parameter, for a 11h daylong recording it gives ~ 66x10 seconds snippets, we keep 10% so we have 6 (or 7 if we take the ceiling value)x2 minutes snippets, so we end up with only 1x5minutes audio. 

Other than that, I tested it (with the default parameters listed above) on some daylong recording and I end up with only 1x5minutes segment, but with lots of speech (1 person talking without interruption) !

**Comment by riebling** [comment]
https://github.com/srvk/DiViMe/issues/12#issuecomment-419382789

> By default, I included it in the tools/ folder in the VM (alongside the diartk, noisemes, etc.. tools), and built it so that it treats one daylong recording at a time, by mimicking the use of the other tools, i.e. `./high_volubility.py data/0396.wav'
notice that since it treats one recording at a time, the command is more precise than the other tools. I could remove that precision and just treat all the recording in data/ , and it would be the same call as the other tools.

I did the same thing for the [chunk.sh](https://github.com/srvk/tools/blob/master/chunk.sh) script that takes a single long audio, a name of a tool, breaks the audio into 5 minute chunks, runs the tool on all of them, then merges the results back into a single, long RTTM. I guess we can create a higher level script to call our scripts repeatedly over a folder full of audio files, if needed.

The difference is that mine doesn't preserve the 5 minute chunks, or use the same naming convention, but rather the default naming convention SOX produces when breaking files into pieces, since the desired output was a single RTTM for the entire input file, not a new subcorpus of smaller files.

**Comment by jukaradayi** [comment]
Update: Should wait for when the Yunitator is completely operationnal to detect key child vocalization - using only a SAD (noisemes) returns mostly adult speakers.

**Comment by MarvinLavechin** [comment]
Update : 
1) Child speech detection has been implemented on the same basis than the SAD. (by counting the total length of the child speech)
2) Parent-child conversations detection has been implemented. Here, we just count the number of exchanges between adults and children. We consider that an exchange is a children and an adult speaking in a row (we consider a maximum 2s-length silence). I was considering the length of the conversation at first, but it didn't work well obviously. In that case, the children's/parent's weight need to be normalized (parents tend to speak much more than children !), counting is a good normalization method.

**Comment by alecristia** [comment]
>
> Thank you!

Could you check whether similarly counts versus duration matters for high
child vocalization selection? That is, does this criterion change the
sample that gets selected? If so, could we have a couple of examples to see
which my colleagues believe is best?

**Comment by MarvinLavechin** [comment]
No problem !

**Comment by MarvinLavechin** [comment]
I edited my reply as a reply (that was a bit useless to keep a "No problem !" answer)

**Comment by MarvinLavechin** [comment]
Update : Add a script (that I won't push on github I think) that evaluates the output of high_volubility.py
Briefly, it compares the human-made transcription (some snippets have been annotated as va-n or tt-n for voice activity, and turntaking) and the extraction made by high_volublity.py :

1) Extracts the relevant part of the .wav file (wrt the human-made transcription) : file1.wav
2) Extracts the 2 relevant minutes from the file returned by high_volubility.py : file2.wav
3) Run yunitator on file1.wav and file2.wav
4) Returns some statistics on these scripts :
    # turn-taking adult-adult
    # turn-taking adult-child
    duration child speech
    duration mal/fem speech
    ....
