### ISSUE TITLE
high_volubility.py: sox warning and yunified.py error

### ISSUE THREAD

**Issue by GladB** [srvk/DiViMe#121]
Running the following

```python utils/high_volubility.py /vagrant/data/ACLEW_high_volubility/0256.wav --diar yunitator_universal --mode CHI --nb_chunks 50 > /vagrant/data/ACLEW_high_volubility/log.txt 2>&1```

the log file contains several sox warnings (eg. `sox WARN wav: Premature EOF on .wav input file`) and one yunified.py error:

```
Traceback (most recent call last):
  File "yunified.py", line 159, in <module>
    for feat in readHtk(INPUT_DIR+"/"+file, HTK_CHUNKSIZE, preSamples):
  File "G/coconut/fileutils/htk.py", line 24, in readHtk
    for i in range(nSamples // chunk_size):
ZeroDivisionError: integer division or modulo by zero
```

That being said, the script does create 50 chunks of high(er) volubility regions, so I am not sure what goes wrong. I assume this is an edge case with the last 5 minutes region of the wav file. Here is the full log file, and 0256.wav is available on databrary.

[log.txt](https://github.com/srvk/DiViMe/files/3142500/log.txt)

**Comment by fmetze** [comment]
i don’t have access to this file right now, but i could see one way for this to occur. can you pull the latest version and try now? Look for instances of "You seem to have very little free memory. Things may be slow.” in the log file

**Comment by GladB** [comment]
After pulling the latest version, I do have instances of "You seem to have very little free memory. Things may be slow.” but the error is still there (although it still does not seem to impact the output which consists of 50 .wav chunks)

**Comment by fmetze** [comment]
I made the temporary directory unique by default, and tested that something like

utils/high_volubility.py [...] --temp TempDir

works as expected. I also tweaked the logic for the memory check, and added diagnostics and assertions to the code, including one of the underlying libraries. Can you please try again (it's best to build the VM from scratch).

If there is still errors, please send me the entire output of the script, and I will probably need the file that causes the problem to be able to debug further.

**Comment by GladB** [comment]
No more warning or error showing up, and the --temp parameter does not throw an error anymore, thank you!

**Comment by fmetze** [comment]
ok, closing

**Comment by GladB** [comment]
A similar error (I assume raised by what was written to fix the previous one) appeared again in the processing of 3 files (out of 42): 1836 (BER), 7085 (ROW) and 9959 (ROS). 

The error is:
```
Traceback (most recent call last):
  File "yunified.py", line 159, in <module>
    for feat in readHtk(INPUT_DIR+"/"+file, HTK_CHUNKSIZE, preSamples):
  File "G/coconut/fileutils/htk.py", line 19, in readHtk
    assert nSamples > 0, "nSamples needs to be > 0"
AssertionError: nSamples needs to be > 0
```


The daylong .wav can be retrieved on OwnCloud (https://owncloud.gwdg.de/index.php/apps/files/?dir=/ACLEW_data/03-raw_data/01-raw_data/aclew_annotations_available/recordings_with_only_high_volubility_annotated_clips&fileid=533262367) or Databrary (https://nyu.databrary.org/volume/389). I am attaching the log files corresponding to these three recordings being processed by `high_volubility.py`.

[log_files.zip](https://github.com/srvk/DiViMe/files/3281637/log_files.zip)
