### ISSUE TITLE
high_volubility.py: output directory for .wav and .rttm

### ISSUE THREAD

**Issue by GladB** [srvk/DiViMe#123]
Is there a parameter that I am not aware of that allows the user to choose where the output wav and rttm files will be stored, and if not, would it be possible to add that parameter? Otherwise the output of one run with a set of parameters gets overwritten by the following run with another set of parameters (one fix is to have several copies of the same file in different directories to run different versions of the script on one wav file, but it is not viable for daylong files)

**Comment by fmetze** [comment]
I added an "--output" switch
