### ISSUE TITLE
high_volubility.py: wav files not copied in output folder

### ISSUE THREAD

**Issue by GladB** [srvk/DiViMe#124]
When an output folder is specified, the wav chunks that should be created by the script are not copied from the temp folder to the output folder (see line https://github.com/srvk/DiViMe/blob/master/utils/high_volubility.py#L167). I guess removing the second `not`  (in `not fin.endswith('.wav')`) on that line would solve the issue?

**Comment by fmetze** [comment]
It seems like the right thing to do given the section header is "# after the model has finished running, remove the wav files" - i.e. the wav files are temporary and should not show up in the output folder. If it is desired that the wav files show up in the output, it can be changed easily (or another flag could be added). Just let me know.

**Comment by GladB** [comment]
Yes we do need to retrieve them at the end (I think the previous version of the script did return the .wav chunks corresponding to the selected high volume regions)

**Comment by fmetze** [comment]
Ok, I reverted it back. The code will only copy new files, but not overwrite existing files in output_dir, which may lead to inconsistent file sets, now that output_dir can be configured.
