### ISSUE TITLE
Installation check result mismatch

### ISSUE THREAD

**Issue by marisacasillas** [srvk/DiViMe#132]
I was able to follow the installation instructions (with Vagrant 2.2.4; see issue #130). To verify that it was working, I ran the installation check recommended in the docs.

``` console
$ vagrant ssh -c "launcher/test.sh"
```

My results don't all line up nicely with the reference results. In particular, the values for **VCM (mine: 65.9; ref: 24.7)** and the **Yuninator (mine: 145.8; ref: 302)** look fairly different—I could be misunderstanding something since there's another reference value (BN32_010007_test.rttm) that doesn't appear to match well to any result from my version of the VM. _The installation check does note that the Yuninator 'failed' (see below)._

Can I trust these results?
``` console
m14404737:DiViMe marcas$ vagrant ssh -c "launcher/test.sh"
Starting tests
Downloading test transcript...
Downloading test audio...
Checking for HTK...
   HTK missing. You can probably ignore this warning, HTK is no longer needed.
Testing noisemes...
Noisemes passed the test.
Testing OpenSmile SAD...
OpenSmile SAD passed the test.
Testing ToCombo SAD...
TOCOMBO SAD passed the test.
Testing DIARTK...
DiarTK passed the test.
Testing Yunitator...
   Yunitator failed - no output RTTM
Testing the evaluation pipeline...
Fontconfig warning: ignoring UTF-8: not a valid region tag
The evaluation pipeline passed the test.
Testing VCM...
VCM passed the test.
Testing WCE...
WCE passed the test
Some tools did not pass the test, but you can still use others
######################################################################################
To wrap up, we will print out the results of the analyses that we ran during the test.
Compare the following results, corresponding to your system, against the reference results printed out below.
If the numbers are similar, then your system is working similarly to the original one.
If you see bigger changes, then please paste this output onto an issue on https://github.com/srvk/DiViMe/issues/.
RESULTS:
LINES: 10	DURATION SUM: 296.23	FILE: /vagrant/data/VanDam-Daylong/BN32/test/diartk_goldSad_BN32_010007_test.rttm
LINES: 36	DURATION SUM: 31	FILE: /vagrant/data/VanDam-Daylong/BN32/test/noisemesSad_BN32_010007_test.rttm
LINES: 88	DURATION SUM: 212.22	FILE: /vagrant/data/VanDam-Daylong/BN32/test/opensmileSad_BN32_010007_test.rttm
LINES: 56	DURATION SUM: 63.66	FILE: /vagrant/data/VanDam-Daylong/BN32/test/tocomboSad_BN32_010007_test.rttm
LINES: 36	DURATION SUM: 65.9	FILE: /vagrant/data/VanDam-Daylong/BN32/test/vcm_BN32_010007_test.rttm
LINES: 83	DURATION SUM: 145.8	FILE: /vagrant/data/VanDam-Daylong/BN32/test/yunitator_universal_BN32_010007_test.rttm
****** REFERENCE RESULTS BEGINS ******.
LINES: 101	DURATION SUM: 298.637	FILE: /vagrant/data/VanDam-Daylong/BN32/test/BN32_010007_test.rttm
LINES: 101	DURATION SUM: 298.637	FILE: /vagrant/data/VanDam-Daylong/BN32/test/diartk_goldSad_BN32_010007_test.rttm
LINES: 37	DURATION SUM: 31.9	FILE: /vagrant/data/VanDam-Daylong/BN32/test/noisemesSad_BN32_010007_test.rttm
LINES: 88	DURATION SUM: 212.22	FILE: /vagrant/data/VanDam-Daylong/BN32/test/opensmileSad_BN32_010007_test.rttm
LINES: 56	DURATION SUM: 63.66	FILE: /vagrant/data/VanDam-Daylong/BN32/test/tocomboSad_BN32_010007_test.rttm
LINES: 31	DURATION SUM: 24.7	FILE: /vagrant/data/VanDam-Daylong/BN32/test/vcm_BN32_010007_test.rttm
LINES: 105	DURATION SUM: 302	FILE: /vagrant/data/VanDam-Daylong/BN32/test/yunitator_BN32_010007_test.rttm
****** REFERENCE RESULTS ENDS ******.
Evaluation pipeline:

Evaluating noisemesSad on /vagrant/data/VanDam-Daylong/BN32/test with respect to : accuracy

Pairs that have been found : 
BN32_010007_test.rttm / noisemesSad_BN32_010007_test.rttm 

accuracy report
                      detection accuracy true positive true negative false positive false negative
                                       %                                                          
item                                                                                              
BN32_010007_test.rttm              11.24         30.80          3.11           0.20         267.57
TOTAL                              11.24         30.80          3.11           0.20         267.57
accuracy report
                      detection accuracy true positive true negative false positive false 
                                       %                                                  
item                                                                                      
BN32_010007_test.rttm              11.24         30.80          3.11           0.20         267.57
TOTAL                              11.24         30.80          3.11           0.20         267.57
Connection to 127.0.0.1 closed.
```

**Comment by marisacasillas** [comment]
@fmetze any ideas about this? ^^

**Comment by fmetze** [comment]
I think this is fine. Your results align perfectly with the results I got, and put into https://github.com/srvk/DiViMe/blob/master/example-logs/launcher-test.log

I think I fixed the Yunitator bug since, but I'll try to take another look over the next couple of days, although I am not sure I will have time.

For all I can tell, we did make some changes to the code since the original reference results have been created. To me, the differences look reasonable, and can be explained by different software versions, etc. It would be good to have someone look at all these results, and decide if they are reasonable from an end-user perspective, or if maybe a completely different test should be run.

**Comment by marisacasillas** [comment]
Thanks very much! That's reassuring. Two notes:

1. It's difficult for an end user to know when a test discrepancy is a
problem: they don't know how big of a difference to expect (e.g.,
"differences of less than ~N are acceptable"). That number should be part
of the test output instruction and/or added to the docs. Could someone on
the DiViMe team please add the information somewhere?

2. Could you clarify on having a user look at the results? Do you just mean
from a hand annotation standpoint on the test file alone? Or a systematic
test on other files? (Or something else?)

**Comment by fmetze** [comment]
Ad 1 - I hear you, but I don’t have a good answer myself. We should probably collect 10 outputs (maybe at the upcoming CogSci workshop?) and see what the mean value and the standard deviation is for values that people are getting. Then we know how much variation is “to be expected”. 

Ad 2 - we would need someone to actually compare the hand annotation with the automatic output on some “reasonable” test file and certify that “this is a good and reasonable output”. I want to avoid a situation in which the system “reliably produces garbage”.

**Comment by ebergelson** [comment]
chiming in
1) in case it's useful, my output is identical to @marisacasillas's above, so i don't know what variability sources are, but there's that. 24.7 vs. 65.9 for vcm_BN32_010007_test.rttm seems like a big difference but i don't know what that's corresponds to, practically speaking. can you clarify?

2) yes-- @fmetze can you make that happen?? would be a huge boon.
