### ISSUE TITLE
Unclear instructions for evaluation

### ISSUE THREAD

**Issue by marisacasillas** [srvk/DiViMe#138]
I haven't been able to try the evaluation tool because of #135, however, I noticed that the instructions are less informative than they could be in [the docs](https://divime.readthedocs.io/en/latest/usage.html). In particular:

**data/:** This second argument tells DiViMe where are the sound files that need to be evaluated. This directory must contain both the annotations generated by the model and the human-made ones.

I _assume_ that it'll look for pairs of outputs like:
- my_file1.rttm, opensmileSad_my_file1.rttm
- my_file2.rttm, noisemesSad_my_file1.rttm

...but it's not clear from the example and maybe depends a little too much on the user's understanding of how you've set things up. A little more detail in the example would do the trick, thanks!

**Comment by alecristia** [comment]
@fmetze just assigning it to you because you were looking over the instructions. The error Middy talks about at the beginning (#135) I'll address in a separate issue. Here, we just need to attend to her pointing out that the instructions are not clear enough

**Comment by alecristia** [comment]
actually, I'm working on this section, so I'll fix this
