### ISSUE TITLE
Compound problem with AWS

### ISSUE THREAD

**Issue by bfmalle** [srvk/DiViMe#145]
MacBook Pro (15-inch, 2017), 2.8 GHz Intel Core i7, 16 GB 2133 MHz LPDDR3, MacOS 10.14.5

After installing the plugins as per instructions, the following errors show up.  

$ vagrant up
There are errors in the configuration of this machine. Please fix
the following errors and try again:

AWS Provider:
* One or more of the needed AWS credentials are missing. No environment variables
are set nor profile 'default' exists at '/Users/bfmalle/.aws/'
* An access key ID must be specified via "access_key_id"
* A secret access key is required via "secret_access_key"
* An AMI must be configured via "ami" (region: #{region})

I verified that the AWS plugin was installed:

Installed the plugin 'vagrant-aws (0.7.2)'!

**Comment by fmetze** [comment]
Do you want to run the VM on AWS, or locally, using Virtualbox?

**Comment by bfmalle** [comment]
I followed Florian's advice to run using Virtualbox.  Installed Virtualbox, tried again (vigrant up).  First time it still gave an error:

Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.

But then I ran it again a little later, and it started the install.  New issues came up, and so I am creating a new thread.

**Comment by fmetze** [comment]
Closing because new issues were opened for the next problems.
