### ISSUE TITLE
Problem with filenames including underscores?

### ISSUE THREAD

**Issue by marisacasillas** [srvk/DiViMe#146]
Help!
I'm on a Mac thing!
Errors!!
:D

**Comment by orasanen** [comment]
There was a bug in the pipeline that couldn't handle underscores in filenames, as underscore was also used to separate SAD name from the original file name in the intermediate files produced by the SAD(s). This caused errors in splitting longer files into utterance-sized chunks for WCE calculation. This error should be now fixed.

A quick way to get the update (without doing vagrant destroy + git pull + vagrant up) is to run:
$ vagrant up
$ ssh vagrant
$ cd ~/repos/WCE_VM/
$ git pull
