### ISSUE TITLE
analyze.sh script expects wav_tmp/WCE_output file it didn't create

### ISSUE THREAD

**Issue by dswingley** [srvk/DiViMe#147]
Q: can analyze.sh work with only a wav file as the input, or does it expect prior annotation files?  I get a fatal "no such file" error, see below

## starting from data directory with only a wav file in it:
swingley-16:DiViMe swingley_16$ ll data/cogsci19/
-rw-r--r--  1 swingley_16  staff  5292044 Jul 24 11:52 f1x120sNorm.wav

## run analyze.sh script
swingley-16:DiViMe swingley_16$ vagrant ssh -c "analyze.sh data/cogsci19"
(MSG) ÿ2¦ in SMILExtract : openSMILE starting!
(MSG) ÿ2¦ in SMILExtract : config file is: MED_2s_100ms_htk.conf
(MSG) ÿ2¦ in cComponentManager : successfully registered 96 component types.
(MSG) ÿ2¦ in cComponentManager : successfully finished createInstances
                                 (19 component instances were finalised, 1 data memories were finalised)
(MSG) ÿ2¦ in cComponentManager : starting single thread processing loop
(MSG) ÿ2¦ in cComponentManager : Processing finished! System ran for 11997 ticks.
Traceback (most recent call last):
  File "/home/vagrant/repos/WCE_VM/aux_VM/WCE_to_rttm.py", line 20, in <module>
    with open(WCE_file, 'rt') as f:
IOError: ÿErrno 2¦ No such file or directory: '/vagrant/data/cogsci19/wav_tmp/WCE_output.txt'
/home/vagrant/utils/analyze.sh: line 40: /vagrant/data/cogsci19/detailed_outputs/WCE_yunitator_english_f1x120sNorm.rttm: No such file or directory
paste: /vagrant/data/cogsci19/wce.temp: No such file or directory
Connection to 127.0.0.1 closed.

## the script did produce some things:
swingley-16:DiViMe swingley_16$ ll data/cogsci19/
total 10368
drwxr-xr-x  4 swingley_16  staff      128 Jul 24 11:53 detailed_outputs
-rw-r--r--  1 swingley_16  staff      235 Jul 24 11:53 f1x120sNorm.rttm.txt
-rw-r--r--  1 swingley_16  staff      198 Jul 24 11:53 f1x120sNorm.rttm_forELAN.txt
-rw-r--r--  1 swingley_16  staff  5292044 Jul 24 11:52 f1x120sNorm.wav
-rw-r--r--  1 swingley_16  staff       17 Jul 24 11:53 files.txt
drwxr-xr-x  5 swingley_16  staff      160 Jul 24 11:52 logs

swingley-16:DiViMe swingley_16$ l data/cogsci19/detailed_outputs/
vcm_f1x120sNorm.rttm			yunitator_english_f1x120sNorm.rttm*
swingley-16:DiViMe swingley_16$ l data/cogsci19/logs
WCE.log		vcm.log		yunitate.log

## yunitate log file 
> wc data/cogsci19/logs/yunitate.log 
      50     153     719 data/cogsci19/logs/yunitate.log
> head data/cogsci19/logs/yunitate.log 
wavs and transcriptions found !
Tests finished
Starting /home/vagrant/launcher/yunitate.sh
Extracting features for f1x120sNorm.wav ...
DONE!
python yunified.py yunitator /vagrant/data/cogsci19 4000 english
0	0	74
0	85	130
0	136	151
0	160	193
# [...]

## input wav file characteristics:
swingley-16:DiViMe swingley_16$ soxi data/cogsci19/f1x120sNorm.wav 
Input File     : 'data/cogsci19/f1x120sNorm.wav'
Channels       : 1
Sample Rate    : 22050
Precision      : 16-bit
Duration       : 00:02:00.00 = 2646000 samples ´ 9000 CDDA sectors
File Size      : 5.29M
Bit Rate       : 353k
Sample Encoding: 16-bit Signed Integer PCM

**Comment by alecristia** [comment]
Sorry, this looks like a bug we created. My reading is that WCE didn't function. I'm adding Okko to ask, has it been tested with 2h long files? @orasanen notice the error comes here:

> File "/home/vagrant/repos/WCE_VM/aux_VM/WCE_to_rttm.py", line 20, in 
> with open(WCE_file, 'rt') as f:
> IOError: ÿErrno 2¦ No such file or directory: '/vagrant/data/cogsci19/wav_tmp/WCE_output.txt'
> 

I may need to add a fix in case this happens, if your rttm.txt & rttm_forELAN.txt are ill-formed. Could you please paste in a reply the first few lines of each?

Thanks for the bug report, keep 'em coming!

**Comment by dswingley** [comment]
swingley-16:cogsci19 swingley_16$ head -6 f*rttm*
==> f1x120sNorm.rttm.txt <==
	¨vcm¾ C¼						<NA>	
	¨vcm¾ CRY¼						<NA>	
	¨vcm¾ N¼						<NA>	
	¨vcm¾ N¼						<NA>	
	¨vcm¾ N¼						<NA>	
	¨vcm¾ N¼						<NA>	

==> f1x120sNorm.rttm_forELAN.txt <==
-wce,,,,
-wce,,,,
-wce,,,,
-wce,,,,
-wce,,,,
-wce,,,,

**Comment by orasanen** [comment]
There was a bug in the pipeline that couldn't handle underscores in filenames, as underscore was also used to separate SAD name from the original file name in the intermediate files produced by the SAD(s). This caused errors in splitting longer files into utterance-sized chunks for WCE calculation. This error should be now fixed. 

A quick way to get the update (without doing vagrant destroy + git pull + vagrant up) is to run:
$ vagrant up
$ ssh vagrant
$ cd ~/repos/WCE_VM/
$ git pull

**Comment by dswingley** [comment]
## hm, tried this and didn't get past step 2.
swingley-16:DiViMe swingley_16$ `vagrant up`
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' version '20190429.0.1' is up to date...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
swingley-16:DiViMe swingley_16$ `ssh vagrant`
ssh: Could not resolve hostname vagrant: nodename nor servname provided, or not known

(sorry, this would probably easy if I read up on vagrant, apologies if this is a no-brainer)

**Comment by fmetze** [comment]
should probably read "vagrant ssh" rather than "ssh vagrant"
