### ISSUE TITLE
DiViMe on Google Cloud and tests not passing 

### ISSUE THREAD

**Issue by prlabu** [srvk/DiViMe#156]
We are trying to use DiViMe with Google Cloud. After a fair amount of debugging and playing around with the Vagrantfile, we at least got what seemed like a proper install with all the packages on the Google Cloud Compute VM instance. 

Here are the updated lines in Vagrantfile for `vagrant up --provider=google`, using the google [vagrant-google](https://github.com/mitchellh/vagrant-google) plugin.
```
  config.vm.provider :google do |google, override|
    google.google_project_id = "MY_PROJECT_ID"
    google.google_json_key_location = "/my/google/key/google-key.json"
    
    google.image_family = 'ubuntu-1604-lts'  
    google.machine_type = 'n1-standard-4'    # 4 CPUs, 15GB RAM
    google.disk_size = '30'                   # 30GB boot disk
    google.zone = "us-central1-a"
    
    override.vm.box = "google/gce"
    override.ssh.username = "MY_GCP_USER"
    override.ssh.private_key_path = "~/.ssh/id_rsa"
    # override.ssh.private_key_path = "~/.ssh/google_compute_engine"

    override.vm.synced_folder ".", "/vagrant", type: "sshfs", ssh_username: "MY_GCP_USER", ssh_port: "22", prompt_for_password: "true"
  end
```

However, when we run `vagrant ssh -c "launcher/test.sh"`, not one of the tests passes. I've searched briefly for related issues. I'd have a different approach if just one or two of them failed - but with all of them failing, there must be something fundamentally wrong with the setup. Is it most likely related to GCP/GCE, or could it be a DiViMe issue? Any suggested debug approaches? Sorry I don't have a more specific question.  

```
groups: cannot find name for group ID 1335747347
Welcome to DiViMe's test.sh
$ git show-branch
[master] Merge branch 'master' of https://github.com/srvk/DiViMe
$ git log -1
commit ff79e83d37cc8be0c7f6076074b1d8ce3f0d73e9
Merge: 1fe83b3 2af7906
Author: Florian Metze <fmetze@cs.cmu.edu>
Date:   Mon Jul 29 11:47:29 2019 +0200

    Merge branch 'master' of https://github.com/srvk/DiViMe
$ git diff --name-status
M       Vagrantfile
################################################################################
Starting tests
Downloading test transcript...
launcher/test.sh: line 52: unzip: command not found
launcher/test.sh: line 56: cd: VanDam-Daylong/BN32/: No such file or directory
Downloading test audio...
Testing noisemes...
   Noisemes failed - dependencies
   Noisemes failed - no RTTM output
Testing OpenSmile SAD...
launcher/test.sh: line 117: /home/vagrant/launcher/opensmileSad.sh: No such file or directory
   OpenSmile SAD failed - dependencies
   OpenSmile SAD failed - no RTTM output
Testing ToCombo SAD...
   ToCombo SAD failed - dependencies
   ToCombo SAD failed - no output RTTM
Testing DiarTk...
   DiarTk failed - no output RTTM
Testing Yunitator...
   Yunitator failed - dependencies
   Yunitator failed - no output RTTM
Testing the evaluation pipeline...
launcher/test.sh: line 179: /home/vagrant/launcher/eval.sh: No such file or directory
   The evaluation pipeline failed - dependencies
   The evaluation pipeline failed the test - output does not match expected
Testing VCM...
   VCM failed - dependencies
   VCM failed - no output RTTM
Testing WCE...
Running WCE module (this might take a while...)
/home/plb1_rice_edu/repos/WCE_VM/WCEestimate: error while loading shared libraries: libmwlaunchermain.so: cannot open shared object file: No such file or directory
paste: data/VanDam-Daylong/BN32/test/: No such file or directory
WCE processing complete. Wrote output to /vagrant/data/test/WCE_BN32_010007_test.csv
WCE tests failed
Some tools did not pass the test, but you can still use others
################################################################################
To wrap up, we will print out the results of the analyses that we ran during the test.
Compare the following results against the reference results printed out below.
If the numbers are similar, then your system is working ok.
If you see bigger changes, then please paste this output onto an issue on https://github.com/srvk/DiViMe/issues/.
****** YOUR RESULTS BEGIN ******.
launcher/test.sh: line 228: /home/vagrant/utils/sum-rttm.sh: No such file or directory
****** REFERENCE RESULTS BEGIN ******.
LINES: 101	DURATION SUM: 298.637	FILE: /vagrant/data/VanDam-Daylong/BN32/test/BN32_010007_test.rttm
LINES: 10	DURATION SUM: 296.23	FILE: /vagrant/data/VanDam-Daylong/BN32/test/diartk_goldSad_BN32_010007_test.rttm
LINES: 37	DURATION SUM: 31.9	FILE: /vagrant/data/VanDam-Daylong/BN32/test/noisemesSad_BN32_010007_test.rttm
LINES: 88	DURATION SUM: 212.22	FILE: /vagrant/data/VanDam-Daylong/BN32/test/opensmileSad_BN32_010007_test.rttm
LINES: 56	DURATION SUM: 63.66	FILE: /vagrant/data/VanDam-Daylong/BN32/test/tocomboSad_BN32_010007_test.rttm
LINES: 31	DURATION SUM: 24.7	FILE: /vagrant/data/VanDam-Daylong/BN32/test/vcm_BN32_010007_test.rttm
LINES: 60	DURATION SUM: 42.3	FILE: /vagrant/data/VanDam-Daylong/BN32/test/yunitator_BN32_010007_test.rttm
****** REFERENCE RESULTS END ******.
Evaluation pipeline YOURS:
cat: /vagrant/data/VanDam-Daylong/BN32/test/eval-test.log: No such file or directory
Evaluation pipeline REFERENCE:
                      detection accuracy true positive true negative false positive false
                                       %
item
BN32_010007_test.rttm              11.24         30.80          3.11           0.20         267.57
TOTAL                              11.24         30.80          3.11           0.20         267.57
Connection to 34.68.160.41 closed.
```
The host machine is a 2017 Macbook running Mojave 10.14.5, 8GB RAM.

**Comment by prlabu** [comment]
Inspecting `launcher/test.sh`, I see that it's looking in `/home/vagrant/` for launchers, repos, and utils. 
 
My setup doesn't seem to align with this - I have 
```
/home/MY_USER
/home/ubuntu
``` 
but no `/home/vagrant`.  Is this something that would have been set up in the Vagrantfile?  
My vagrant directory with launchers, repos, and utils lives at `/vagrant`.

**Comment by prlabu** [comment]
I've been trying more configurations for the Vagrantfile, but to no avail. Here's the stdout log for installation: [vagrant-up.log](https://github.com/srvk/DiViMe/files/3899330/vagrant-up.log). I've compared them to the log in the DiViMe `log/vagrant-up.log`. In particular, I'm wondering about lines 210-225...
```
default: md5sum: 
    default: /vagrant/MCR_R2017b_glnxa64_installer.zip
    default: : No such file or directory
    default: /vagrant/MCR_R2017b_glnxa64_installer.zip: FAILED open or read
    default: md5sum: WARNING: 1 listed file could not be read
    default: Hit http://archive.canonical.com trusty Release
    default: Hit http://archive.canonical.com trusty/partner amd64 Packages
    default: md5sum: /vagrant/Anaconda2-2019.03-Linux-x86_64.sh: No such file or directory
    default: /vagrant/Anaconda2-2019.03-Linux-x86_64.sh: FAILED open or read
    default: md5sum: WARNING: 1 listed file could not be read
    default: Hit http://archive.canonical.com trusty/partner Translation-en
    default: md5sum: 
    default: /vagrant/opensmile-2-3-0.tar.gz
    default: : No such file or directory
    default: /vagrant/opensmile-2-3-0.tar.gz: FAILED open or read
    default: md5sum: WARNING: 1 listed file could not be read
```
These lines are not found in example log file. For what reason would it not find/read these files in `/vagrant`?

**Comment by fmetze** [comment]
Hm, you should be able to do this, assuming that the google cloud sshfs provides for bi-directional updates (which I think it does). After doing "vagrant up", I see the following on my mac book, using virtual box, not scp:

loriansMBP2019:~ metze$ cd Work/Kitchen/DiViMe
FloriansMBP2019:DiViMe metze$ ls
[...]
Anaconda2-2019.03-Linux-x86_64.sh
HTK-3.4.1.tar.gz
[...]
MCR_R2017b_glnxa64_installer.zip
README.md
Vagrantfile
conf
data
[...]
docs
launcher
logs
org
test
test2.wav
utils
vagrant
FloriansMBP2019:DiViMe metze$ vagrant up
[...]
FloriansMBP2019:DiViMe metze$ vagrant ssh
Welcome to Ubuntu 14.04.6 LTS (GNU/Linux 3.13.0-170-generic x86_64)
[...]
Last login: Wed Jul 24 21:30:56 2019 from 10.0.2.2
vagrant@vagrant-ubuntu-trusty-64:~$ ls /home/
ubuntu  vagrant
vagrant@vagrant-ubuntu-trusty-64:~$ ls /home/ubuntu/
vagrant@vagrant-ubuntu-trusty-64:~$ ls /home/vagrant/
anaconda  bin  data  launcher  repos  utils
vagrant@vagrant-ubuntu-trusty-64:~$ ls /vagrant/
[...]
Anaconda2-2019.03-Linux-x86_64.sh
conf
data
[...]
docs
HTK-3.4.1.tar.gz
[...]
launcher
LICENSE
logs
MCR_R2017b_glnxa64_installer.zip
org
README.md
test
test2.wav
utils
vagrant
Vagrantfile

So I think how the directories match. Maybe you need gcp to use "vagrant" as your user name?

**Comment by prlabu** [comment]
Thanks for the suggestion! I currently am looking into it, but it's not straightforward due to security measures - my ssh username from this computer is set by GCE such that it is recognized when trying to connect with a VM.
When I change my ssh username to 'vagrant' or 'ubuntu' in the Vagrantfile, I get an ssh-timeout error while initializing the instance. 

I was trying to go off of the AWS setup specified in the Vagrantfile, where the ssh username is 'ubuntu' and the sshfs username is the user from the env variables -- neither of which are the "vagrant" username that the tests and other DiViMe scripts expect...
`    override.vm.synced_folder ".", "/vagrant", type: "sshfs", ssh_username: ENV['USER'], ssh_port: "22", prompt_for_password: "true"
`
`override.ssh.username = "ubuntu"`
I wonder how it's working on AWS without the 'vagrant' username.

Part of the issue with debugging is that it takes at least an hour and a half (sometimes more) for the installation to work (or fail). I know it says >~15 mins on the installation guide for a local VirtualBox setup -- should it take longer for cloud services?

**Comment by fmetze** [comment]
hm, the "synced folder" is the local main experiment folder (on your computer), which gets mounted to the VM as /vagrant. This is different from the VM's home directory /home/vagrant (or /home/ubuntu). i think you can probably debug interactively - let vagrant run as far as it can go, then try to get the missing things done manually to see what works, and how.

local installs can be fast because we are caching the large downloads for Matlab, etc. Depending on your network connectivity, these can be quite slow, and if you have a cloud installation, even the cached file will need to be uploaded to the cloud again (and it may be faster for google to get the download directly from the source, than from your computer via sshfs - but this only starts to matter once you are in the shell script part of the installation)

**Comment by prlabu** [comment]
By "get missing things done manually", do you mean going through `conf/bootstrap.sh`, `conf/bootstrap-user.sh`, `conf/bootstrap-system.sh` and trying to run the bash commands individually?

**Comment by fmetze** [comment]
Not necessarily individually, but in groups, etc - as seems useful, to see if required input files exist, output files have been created, etc. It seems that the build process fails early on, before the shell scripts get executed, so I would expect that you will be able to diagnose the problem early on.

**Comment by prlabu** [comment]
_Resolved:_ 
We ended up adding the following to Vagrantfile, in combination with [vagrant-google](https://github.com/mitchellh/vagrant-google) plugin. 

```
  config.vm.provider :google do |google, override|
    google.google_project_id = "tugofwords"
    google.google_json_key_location = "/Users/myusername/Documents/path_to_creds/project_credentials.json"
    
    google.image_family = 'ubuntu-1404-lts'  
    google.machine_type = 'n1-standard-4'    # 4 CPUs, 15GB RAM
    google.disk_size = '30'                   # 30GB boot disk
    google.zone = "us-central1-a"
    google.name = "divime" # can be any name you like
    
    override.vm.box = "google/gce"
    override.ssh.username = "vagrant"
    override.ssh.private_key_path = "~/.ssh/vagrant"
    # override.ssh.private_key_path = "~/.ssh/google_compute_engine"

    override.vm.synced_folder ".", "/vagrant", type: "sshfs"
  end
```

**Make sure you have the enable-oslogin key set to FALSE** in the GCE Metadata. 
We struggled for a long time figuring this out. 

I believe you should be able to change the machine type and disk size config, but leave `google.image_family` as `ubuntu-1404-lts`. 

It still takes about 4-5 hours for `vagrant up` to finish. 

Feel free to reach out to me if you are trying to get DiViMe set up on GCP.
