### ISSUE TITLE
yunitator with 2 classes: target child vs. all other speakers

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#16]
that is, distinguish key child (one class) versus all others (another class containing mother, all female adults, male adults, other children, none)

**Comment by alecristia** [comment]
datasets that could be used for this:
- vandam (already processed)
- namvan + tsi (idem)
- ASE (idem)

All of the following need to be processed:
- ACLEW round 1-3 
- CHILDES paidologos with added noise OR mixed in with recordings known to have only one child talking to simulate presence of other children
- IDS/ADS samples

**Comment by riebling** [comment]
Hopefully this is trivial; you could imagine just filtering the RTTM produced by Yunitator with sed and awk, replacing class labels other than CHI from the set of, as I recall:
```
CHI
FEM
MAL
SIL
```

**Comment by fmetze** [comment]
I think the main idea is to train a new Yunitator on "ACLEW round 1-3" data in addition to Vandam and ASE (ACLEW Starter) - not sure if CHILDES and IDS/ADS samples are available.

**Comment by alecristia** [comment]
I second Eric's comment -- it might be good to get started with the data you already have, even if we'll increase the training set later on (which might make for a nice experiment anyway). Remember that the data folks are waiting for this tool to do their next round of sampling.

All of the data I mentioned are already available. All that remains is to format the annotations in the same format you have used before. Here are the links:

CHILDES Paidologos:
- annotations: https://www.dropbox.com/sh/3t9kkfzdh726rft/AABxsGG3QkQ2Fu_g68JoG7Bja?dl=0
- sounds:
To get the sound files, the following worked 6 months ago:
wget -c robots=off -r -l inf --no-remove-listing -nH --no-parent -R 'index.html*' http://media.talkbank.org/PhonBank/Chinese/Cantonese/PaidoCantonese/
wget -c robots=off -r -l inf --no-remove-listing -nH --no-parent -R 'index.html*' http://media.talkbank.org/PhonBank/Eng-NA/PaidoEnglish/
wget -c robots=off -r -l inf --no-remove-listing -nH --no-parent -R 'index.html*' http://media.talkbank.org/PhonBank/Japanese/PaidoJapanese/
wget -c robots=off -r -l inf --no-remove-listing -nH --no-parent -R 'index.html*' http://media.talkbank.org/PhonBank/Other/Greek/PaidoGreek/

IDS/ADS samples:
- available from https://media.talkbank.org/HomeBank/Password/IDSLabel with password -- I'll send a separate email about that

**Comment by riebling** [comment]
Oh good. I also just had to request the latest media.talkbank.org data password, and can supply if needed.

**Comment by riebling** [comment]
This is maybe the second situation where we'd like to train up a new Yunitator variant. Maybe we can generalize and create a task for Yun: produce documentation and give examples of how we ("a novice") can train Yunitator on new data to produce new models & class labels?

**Comment by alecristia** [comment]
Closing this issue - this is a suboptimal solution, and we should focus our forces on better ones (eg 4- or 5-class labeling.)

**Comment by riebling** [comment]
I meant that if we can re-train a new Yunitator, it could be on 4- or 5-class labeled data, making it more optimal. Agree the number of classes currently produced by Yunitator is suboptimal.

**Comment by alecristia** [comment]
Oh I meant the 2-class solution that I had brought up in this issue was even more suboptimal (even less optimal?). It was just an idea that came up given the scarcity of data -- but I think we can do better, for instance with the 3 class currently implemented. RE training, I don't think that is a priority given our current user base (ACLEW), since none of us independently have enough data for retraining. In fact, it seems that even all together we don't have enough data for training 3 classes! So a retrainable module sounds more useful in theory than in our current world...
