### ISSUE TITLE
Adapt the ToComboSAD into our pipeline

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#2]
Write wrappers so that it works the same as the other tools (see sample instructions below). This entails:

- [ ] accept WAV input
- [ ] produce RTTM output
- [ ] use standard locations / temp folders

# Target instructions #
For the SAD tools, type a command like the one below, being careful to type the SAD tool name instead of SADTOOLNAME:

`$ vagrant ssh -c "tools/SADTOOLNAME.sh data/"`

The SAD options are:
- SADTOOLNAME = ldc_sad
- SADTOOLNAME = noisemes_sad
- SADTOOLNAME = noisemes_full

This will create a set of new rttm files, with the name of the tool added at the beginning. For example, imagine you have a file called participant23.wav, and you decide to run both the LDC_SAD and the Noisemes analyses. You will run the following commands:

```
$ vagrant ssh -c "tools/ldc_sad.sh data/"
$ vagrant ssh -c "tools/noisemes_sad.sh data/"
```

And this will result in your having the following three files in your /data/ folder:

- participant23.wav
- ldc_sad_participant23.rttm
- noisemes_sad_participant23.rttm

If you look inside one of these .rttm's, say the ldc_sad one, it will look as follows:

```
SPEAKER	participant23	1	0.00	0.77	<NA>	<NA>	speech	<NA>
SPEAKER	participant23	1	0.77	0.61	<NA>	<NA>	nonspeech	<NA>
SPEAKER	participant23	1	1.38	2.14	<NA>	<NA>	speech	<NA>
SPEAKER	participant23	1	3.52	0.82	<NA>	<NA>	nonspeech	<NA>
```

This means that LDC_SAD considered that the first 770 milliseconds of the audio were speech; followed by 610 milliseconds of non-speech, followed by 2.14 seconds of speech; etc.

**Comment by riebling** [comment]
https://github.com/srvk/tools/blob/master/tocombo_sad.sh
