### ISSUE TITLE
add daylong sample file from homebank to the VM test routine

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#21]
Excellent news! There is one public full daylong file up on homebank:
https://homebank.talkbank.org/access/Public/VanDam-Daylong.html

Please use it for the test for daylong files. The citation that should go in the README is:
VanDam, M., & Tully, T. (2016, May). Quantity of mothers’ and fathers’ speech to sons and daughters. Talk presented at the 171st Meeting of the Acoustical Society of America, Salt Lake City, UT.

I think the audio can be pulled with:
 wget -c robots=off -r -l inf --no-remove-listing -nH --no-parent -R 'index.html*' http://media.talkbank.org/HomeBank/VanDam-daylong/ 

The transcripts need to be:

- downloaded from https://homebank.talkbank.org/data/Public/VanDam-Daylong.zip
- unzipped
- processed

I don't think we have any official tools to process .cha --> rttm OR .its --> rttm but both will be useful in the future. I propose we focus on the .cha --> rttm now; here's a snippet that could be modified to produce proper rttms:

for j in *.cha; do 
	grep -v "^@" < $j | grep -v "^%" | tr -d "\t" | sed 's/\([0-9][0-9]*\)_\([0-9][0-9]*\)/%\1%\2/g' | tr "_" "-"  | tr -d "\n" | tr -d "\r" | tr '*' '\n'   | tr ":" "\t" | tr "%" "\t" | tr -s " " | sed 's/^$//' | awk -F'\t' 'NF==4 {print}' >> $j.txt 
done

That will produce a file with this shape:
participant phrase onset offset

where phrase is what has been transcribed, onset and offset are in milliseconds. So it is missing some of the other rttm columns.

**Comment by riebling** [comment]
We have some tools that might do a better job of converting .cha files; they are notoriously strangely formatted (especially with respect to line breaks), such that looking at the raw .cha might miss things. I will find or provide some code that uses the CHATTER program to parse CHA to XML, and then you can pull out values from XML reliably. We've done this for STM format, but maybe not RTTM (but they are quite similar)

**Comment by alecristia** [comment]
to clarify, this is what needs to happen to close this issue:

- [ ] add pulling of daylong file with annotation to the initial installation of the VM - @riebling 
- [ ] add sequence of tests for daylong files to the test routine of the VM - @riebling 
- [ ] make updates (notably citation information) to the VM readme - @alecristia

**Comment by alecristia** [comment]
combined with issue #23
