### ISSUE TITLE
completing the test and improving the test output

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#23]
The test should (1) make reference to each tool in DiViMe and (2) be maximally informative to the user. Right now the output is:

> Testing noisemes...
> Noisemes passed the test.
> Testing DIARTK...
> Source file format: WAV [WAVEFORM]
> Target file format: HTK [MFCC_K]
> Source rate: 625 Target rate: 100000 
> Initialize HMM
>  AIB diarization started at 426400 
> 
> 
>  MFCC:   /tmp/diartk-test/test2.fea  weight MFCC  1 
> 
>  Maximum Segment Duration 250 
> 
> 
>  AIB is running with the following parameters
> 
>  Maximum number of clusters possible: 		10
>  Normalized Mutual Information threshold: 		0.5
>  Beta value: 		10
>  Number of threads: 		3
> 
> 
>  Reading and Processing the scp file 
> number of segments inside = 4
> Number of vectors = 1177
> Feat file /tmp/diartk-test/test2.fea of type 0
> Reading feature file /tmp/diartk-test/test2.fea
> frame dim: 19
> num_vec = 1177
> Attempting memory allocation.
> Memory successully allocated.
> Reading file ... 
> all segments read 
> Number of segments in the file = 7
> num_vec = 1177  idx = 0
> compute features after: 0.003162
> 
> 
>  The matrix seems ok
>  Final Matrix size after zero removal 7 7  
>  The initial MI values are: 0.278116 1.94591 1.89442 
>  Initializing the Delta -- Computing 7 times 7 Distances 
> Running time 0  
> 
> 
>  Now Clustering 
> 
>  Size: 6 Ity: 0.278116 Ht: 1.94591 Ity_div_Itx:  1  Ht_div_Hx:   1
>  Size: 5 Ity: 0.269044 Ht: 1.74787 Ity_div_Itx:  0.96738  Ht_div_Hx:   0.898227
>  Size: 4 Ity: 0.252526 Ht: 1.54983 Ity_div_Itx:  0.90799  Ht_div_Hx:   0.796453
>  Size: 3 Ity: 0.212945 Ht: 1.15374 Ity_div_Itx:  0.76567  Ht_div_Hx:   0.592906
>  Size: 2 Ity: 0.170458 Ht: 0.796312 Ity_div_Itx:  0.612904  Ht_div_Hx:   0.409223
>  Size: 1 Ity: 0.113672 Ht: 0.410116 Ity_div_Itx:  0.408721  Ht_div_Hx:   0.210758
> 
>  Size: 0 Ity: -7.77156e-17 Ht: 3.33067e-16 Ity_div_Itx:  -2.79436e-16  Ht_div_Hx:   1.71163e-16
> Saving this solution 
> 0  -7.77156e-17  0.278116  -2.79436e-16  
> 1  0.113672  0.278116  0.408721  
> 2  0.170458  0.278116  0.612904  
> 3  0.212945  0.278116  0.76567  
> 4  0.252526  0.278116  0.90799  
> 5  0.269044  0.278116  0.96738  
> 6  0.278116  0.278116  1  
> Key to solution 7 NMI value0.5  
>  The clustering has finished. Now saving the solution in /tmp/diartk-test/test2.clust.out
>  ...and saying goodbye 
> 
> 
> last speech frame = 1363 total number of speech frames = 1177
> training the rkl hmm 
> For the Segmentation, nSamples = 1177, nClass = 7
> Segmentation Over with Viterbi score = 178095.156250
> The htk file sample rate 100000 
> Diarization stopped at 426400  
> Running time 0 seconds  
> compute features after: 0.003162
> aib clustering after: 0.001365
> realignment after: 0.027626
> DiarTK passed the test.
> Congratulations, everything is OK!
> Connection to 127.0.0.1 closed.

But the output should be:

> Testing LDC SAD...
> LDC SAD passed the test. OR LDC SAD failed the test because a dependency was missing. Please re-read the README for DiViMe installation, Step number 4 (HTK installation). OR LDC SAD failed because the code for LDC SAD is missing. This is normal, as we are still awaiting the official release!
> 
> Testing Speech Activity Detection Using Noisemes...
> Noisemes passed the test. OR Noisemes failed the test because a dependency was missing. Please re-read the README for DiViMe installation, Step number 4 (HTK installation). 
> 
> Testing OpenSmile SAD...
> OpenSmile SAD passed the test. 
> 
> Testing Threshold Optimized Combo SAD...
> Threshold Optimized Combo SAD passed the test. 
> 
> Testing DiarTK...
> DiarTK passed the test. OR DiarTK failed the test because a dependency was missing. Please re-read the README for DiViMe installation, Step number 4 (HTK installation). 
> 
> Congratulations, everything is OK! OR Some of the tools did not pass the test, but you can still use the other tools.
> This is the simple test with a few short files. If you would like to run a test for use with daylong recordings, please run $ vagrant ssh -c "tools/test-daylong.sh". Note that this will download a very large recording.

And the test-daylong for now would just print a message that we are working on it!

**Comment by alecristia** [comment]
Additions: 

When a given tool passes the test,

- [ ]  copy any *.md found inside the tool's folder into the docs/source folder
- [ ] add a line to index.rst under usage (**formatting to be confirmed**)

At the end of the test,
- [ ] cd into docs
- [ ] do $ make html

**Comment by alecristia** [comment]
Ideal behavior again:

- [ ] download daylong
- [ ] extract audio and cha from https://homebank.talkbank.org/access/Public/VanDam-Daylong.html
- [ ] extract minute XXX-YY from there
- [ ] for each tool, check for presence of tool, presence of dependency, and if both pass, run tool on that clip --> if rttm found, then print OK

example of ok for one tools:

> Testing LDC SAD...
> LDC SAD passed the test. OR LDC SAD failed the test because a dependency was missing. Please re-read the README for DiViMe installation, Step number 4 (HTK installation). OR LDC SAD failed because the code for LDC SAD is missing. This is normal, as we are still awaiting the official release!
> 

example of final ok:
> Congratulations, everything is OK! OR Some of the tools did not pass the test, but you can still use the other tools.

**Comment by alecristia** [comment]
cleaning cha:

for j in *.cha; do 
	cp header.txt $j.txt
	grep -v "^@" < $j | grep -v "^%" | tr -d "\t" | sed 's/\([0-9][0-9]*\)_\([0-9][0-9]*\)/%\1%\2/g' | tr "_" "-"  | tr -d "\n" | tr -d "\r" | tr '*' '\n'   | tr ":" "\t" | tr "%" "\t" | tr -s " " | sed 's/^$//' | awk -F'\t' 'NF==4 {print}' >> $j.txt 

	tail -n +2 < $j.txt | awk '{print $1}' | sort | uniq > $j.ppnt

done

**Comment by riebling** [comment]
vagrant@vagrant-ubuntu-trusty-64:/vagrant/data$ j=BN32_010007.cha
vagrant@vagrant-ubuntu-trusty-64:/vagrant/data$ grep -v "^@" < $j | grep -v "^%" | tr -d "\t" | sed 's/([0-9][0-9]\
)([0-9][0-9]*)/%\1%\2/g' | tr "" "-" | tr -d "\n" | tr -d "\r" | tr '*' '\n' | tr ":" "\t" | tr "%" "\t" | tr -s "\
 " | sed 's/^$//' | awk -F'\t' 'NF==4 {print}' >> $j.txt
sed: -e expression #1, char 36: invalid reference \2 on `s' command's RHS

**Comment by alecristia** [comment]
`grep -v "^@" < $j | grep -v "^%" | tr -d "\t" | sed 's/\([0-9][0-9]*\)_\([0-9][0-9]*\)/%\1%\2/g' | tr "_" "-"  | tr -d "\n" | tr -d "\r" | tr '*' '\n'   | tr ":" "\t" | tr "%" "\t" | tr -s " " | sed 's/^$//' | awk -F'\t' 'NF==4 {print}' >> $j.txt `

**Comment by riebling** [comment]
A little confusing and disappointing to discover that evalSAD.sh and evalDiar.sh use
different scoring code - yet look so similar. In fact, they both call, at the deepest level,
something called `score.py` - well ok, there is a `score.py` in both scoring folders
(`ldc_sad_hmm/` and `dscore/`) 

I was going crazy trying to figure out why "this scoring code" was putting everything into .lab format, and then worse, calling a python score program with these .lab files... when I knew full well that the scoring program `score.py` accepts strictly RTTM format!  DIFFERENT SCORE.PY!

(which is the thing I really things we should be testing... the low level "executables" that do the scoring, not the run / launcher scripts that call them) Ok much less confused now, but just wanted to share my confusion :)

**Comment by riebling** [comment]
Example 'success' output:
```
vagrant@vagrant-ubuntu-trusty-64:~$ tools/test.sh
Testing LDC SAD...
LDC SAD passed the test.
Testing noisemes...
Noisemes passed the test.
Testing OpenSmile SAD...
OpenSmile SAD passed the test.
Testing ToCombo SAD...
TOCOMBO SAD passed the test.
Testing DIARTK...
DiarTK passed the test.
Testing Yunitator...
Yunitator passed the test.
Testing Dscore...
DScore passed the test.
Testing LDC evalSAD
LDC evalSAD passed the test
Congratulations, everything is OK!
```
Daylong audio+RTTM, 5minute _test+_test.rttm, test folders:
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/data$ ls -l VanDam-Daylong/BN32/
total 262308
drwxrwxrwx 1 vagrant vagrant        41 Oct 31 19:54 0its
-rwxrwxrwx 1 vagrant vagrant        81 Oct 31 19:54 1
-rwxrwxrwx 1 vagrant vagrant    512989 Aug  9 16:48 BN32_010007.cha
-rwxrwxrwx 1 vagrant vagrant 255833980 Jun 13 15:42 BN32_010007.mp3
-rwxrwxrwx 1 vagrant vagrant    835838 Oct 31 19:54 BN32_010007.stm
-rwxrwxrwx 1 vagrant vagrant      6103 Oct 31 19:54 BN32_010007_test.rttm
-rwxrwxrwx 1 vagrant vagrant   9600044 Oct 31 19:54 BN32_010007_test.wav
-rwxrwxrwx 1 vagrant vagrant   1793401 Oct 31 19:54 BN32_010007.xml
drwxrwxrwx 1 vagrant vagrant      4096 Oct 31 18:55 diartk-test
drwxrwxrwx 1 vagrant vagrant        96 Oct 31 18:56 dscore-test
drwxrwxrwx 1 vagrant vagrant       125 Oct 31 19:57 ldc_sad-test
drwxrwxrwx 1 vagrant vagrant       109 Oct 31 19:54 noisemes-test
drwxrwxrwx 1 vagrant vagrant       260 Oct 31 19:57 opensmile-test
drwxrwxrwx 1 vagrant vagrant       179 Oct 31 19:56 tocombo_sad-test
drwxrwxrwx 1 vagrant vagrant        92 Oct 31 19:56 yunitator-test
```
Log files:
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/data$ ls -l VanDam-Daylong/BN32/*-test/*.log
-rwxrwxrwx 1 vagrant vagrant   122 Oct 31 19:56 VanDam-Daylong/BN32/diartk-test/diartk-test.log
-rwxrwxrwx 1 vagrant vagrant     0 Oct 31 19:57 VanDam-Daylong/BN32/dscore-test/dscore-test.log
-rwxrwxrwx 1 vagrant vagrant   112 Oct 31 19:57 VanDam-Daylong/BN32/ldc_sad-test/ldc_evalSAD.log
-rwxrwxrwx 1 vagrant vagrant   122 Oct 31 19:54 VanDam-Daylong/BN32/ldc_sad-test/ldc_sad.log
-rwxrwxrwx 1 vagrant vagrant   675 Oct 31 19:55 VanDam-Daylong/BN32/noisemes-test/nosiemes-test.log
-rwxrwxrwx 1 vagrant vagrant    32 Oct 31 19:55 VanDam-Daylong/BN32/opensmile-test/opensmile-test.log
-rwxrwxrwx 1 vagrant vagrant 91931 Oct 31 19:55 VanDam-Daylong/BN32/opensmile-test/opensmile-vad.log
-rwxrwxrwx 1 vagrant vagrant   725 Oct 31 19:56 VanDam-Daylong/BN32/tocombo_sad-test/tocombo_sad_test.log
-rwxrwxrwx 1 vagrant vagrant   583 Oct 31 19:57 VanDam-Daylong/BN32/yunitator-test/yunitator-test.log
```
Test result RTTMs:
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/data$ find VanDam-Daylong -name \*.rttm
VanDam-Daylong/BN32/BN32_010007_test.rttm
VanDam-Daylong/BN32/ldc_sad-test/BN32_010007_test.rttm
VanDam-Daylong/BN32/noisemes-test/hyp_sum/BN32_010007_test.rttm
VanDam-Daylong/BN32/opensmile-test/opensmile_sad_BN32_010007_test.rttm
VanDam-Daylong/BN32/opensmile-test/BN32_010007_test.rttm
VanDam-Daylong/BN32/tocombo_sad-test/tocombo_sad_BN32_010007_test.rttm
VanDam-Daylong/BN32/diartk-test/BN32_010007_test.rttm
VanDam-Daylong/BN32/yunitator-test/Yunitemp/BN32_010007_test.rttm
VanDam-Daylong/BN32/dscore-test/test_ref/Phil_Crane.rttm
VanDam-Daylong/BN32/dscore-test/test_sys/Phil_Crane.rttm
```

**Comment by riebling** [comment]
More testing of the test. Tests explicitly & reports presence of HTK. Reports when DiarTK cannot find HTK. Quiet the output when downloading java for the CHA->STT->RTTM conversion. Test the test for : missing HTK, missing ldc_sad_hmm (most common cases). Test the test launched outside of, and within the VM.

**Comment by riebling** [comment]
I'm thinking this is almost ready to be closed

**Comment by alecristia** [comment]
all that is missing is adding some information about the output at the end of the test to be newbie-readable. I did so, and realized that the firs two lines are suspiciously similar:
LINES: 101	DURATION SUM: 298.637	FILE: /vagrant/data/VanDam-Daylong/BN32/test/BN32_010007_test.rttm
LINES: 101	DURATION SUM: 298.637	FILE: /vagrant/data/VanDam-Daylong/BN32/test/diartk_goldSad_BN32_010007_test.rttm


And that the DScore is still relying on a different file:
Phil_Crane	43.38	0.975590490013	0.672338020576	0.796061934402	0.599223772838	0.963770340456	0.103871357212	1.67823036445	0.793181875273

But I think we can leave these as improvements for the future, so I'm closing this!

**Comment by alecristia** [comment]
strange, I just ran the test twice and the first two lines are NOT identical, but the diartk output is super different in terms of N of lines:
LINES: 101	DURATION SUM: 298.637	FILE: /vagrant/data/VanDam-Daylong/BN32/test/BN32_010007_test.rttm
LINES: 10	DURATION SUM: 296.23	FILE: /vagrant/data/VanDam-Daylong/BN32/test/diartk_goldSad_BN32_010007_test.rttm
