### ISSUE TITLE
adapting behavior to long files

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#32]
Please use vandam daylong file for test

- [ ] LDC Speech Activity Detection: Does it choke with long files? If yes, add Eric's wrapper for chunking. **Make sure that it is not overly slow due to acoustic model reloading for each file**.
- [ ] Speech Activity Detection Using Noisemes: Does it choke with long files? If yes, add Eric's wrapper for chunking. **Make sure that it is not overly slow due to acoustic model reloading for each file**.
- [ ] OpenSmile SAD: Does it choke with long files? If yes, add Eric's wrapper for chunking. **Make sure that it is not overly slow due to acoustic model reloading for each file**.
- [ ] Threshold Optimized Combo SAD: Does it choke with long files? If yes, add Eric's wrapper for chunking. **Make sure that it is not overly slow due to acoustic model reloading for each file**.
- [ ] DiarTK: Does it choke with long files? If yes, remove tool altogether -- it is useless to have this phase over short files
- [ ] Yunitator: Does it choke with long files? If yes, add Eric's wrapper for chunking. **Make sure that it is not overly slow due to acoustic model reloading for each file**.

**Comment by fmetze** [comment]
Yunitator and Noiseme speech activity detection: check progress on #44, TOCombo check #45; there is some information at https://github.com/orgs/srvk/teams/did/discussions/2 on the progress.

**Comment by riebling** [comment]
Here is the wrapper for chunking: https://github.com/srvk/tools/blob/master/chunk.sh
( Tthat breaks audio into 5 minute chunks, calls a named tool launch script in a loop over those chunks, then merges result RTTMs back together. )

**Comment by alecristia** [comment]
I think this issue has been replaced by separate ones on the specific tools
