### ISSUE TITLE
provide advice on a procedure allowing users to easily re-install custom components after a VM update

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#33]
(details in slack conversation with Okko)

**Comment by riebling** [comment]
being addressed by @junghanw as part of https://github.com/srvk/DiViMe/tree/develop/refactor_vagrant

**Comment by alecristia** [comment]
for the specific case of adding htk after the fact, there is a new routine that addresses this (vagrant ssh -c "utils/install_htk.sh").
