### ISSUE TITLE
create tool to check performance of a given tool as a function of file length

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#37]
can be generated using yunitator but the hope is that it can be used with any other tool

**Comment by riebling** [comment]
Here are measurements from running several tools, as a function of file length. This isn't a general tool for producing such measurements, but at least serves as example output from real measurements:
https://docs.google.com/spreadsheets/d/1SYsJoZTW4EnOP86xpIp9WhCn4e1RdzICFBAN45G1zDg/edit#gid=939480220

**Comment by alecristia** [comment]
closing because it's not a priority
