### ISSUE TITLE
Add layer that classifies output of diarization into key roles

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#4]
We need a tool that takes a list of on/off times and classifies each into talker "roles". At the very least, we need the following roles: target child (wearing the recorder) separate from other children, female adults, male adults.

**Comment by jukaradayi** [comment]
this is still important and the current version of the yunitator that Florian showed does not do this, since it assumes unsegmented input

**Comment by fmetze** [comment]
can you elaborate a bit?

in goes an RTTM file with on/ off times, and the output is a file that assigns a speaker label to each line in the input RTTM?

**Comment by riebling** [comment]
That's how I'm interpreting this. I'm working with Yun to see if it's something easy (for example if Yunitator does as a first stage, some form of VAD, then afterward classifies) or possibly hard (for example if it classifies at a frame level, then merges similar frames together to get segments)

My intuition is it's more the latter.

**Comment by riebling** [comment]
The approach is going to be to break up audio into utterances defined by the input SAD
RTTM, call Yunitator repeatedly for each, then if it breaks those utterances into smaller pieces,
select the generated speaker label (for example CHI, FEM, MAL, SIL) that covers the
majority of the time span for that utterance as "the label", then produce an output
RTTM similar to the input RTTM, but with speaker label column filled in for each utterance.

**Comment by riebling** [comment]
Florian mentioned a good second approach: run Yunitator in the normal way, and write code to essentially _merge_ the SAD RTTM input and the Yunitator RTTM output. This helps avoid what will probably be a performance overhead, never mind audio boundary & context problems with running Yunitator over tiny utterance sized audios. For each utterance in the input RTTM, observe the same time period in the Yuntator output RTTM, and whichever speaker ID label occupies the majority of the time span of the input utterance, consider that the output label for that utterance.

**Comment by riebling** [comment]
A first cut at a tool that implements algorithm 1: run Yunitator repeatedly for audio segments defined by input SAD RTTM is nearly ready. It does not necessarily handle elegantly daylong audios. Sample output:
baseline Yunitator
```
SPEAKER test2.rttm      1       0.0     0.6     <NA>    <NA>    FEM     <NA>    <NA>
SPEAKER test2.rttm      1       0.6     0.6     <NA>    <NA>    MAL     <NA>    <NA>
SPEAKER test2.rttm      1       1.2     4.6     <NA>    <NA>    FEM     <NA>    <NA>
SPEAKER test2.rttm      1       5.8     0.5     <NA>    <NA>    SIL     <NA>    <NA>
SPEAKER test2.rttm      1       6.3     3.7     <NA>    <NA>    FEM     <NA>    <NA>
SPEAKER test2.rttm      1       10.0    0.9     <NA>    <NA>    SIL     <NA>    <NA>
SPEAKER test2.rttm      1       10.9    2.9     <NA>    <NA>    FEM     <NA>    <NA>
SPEAKER test2.rttm      1       13.8    2.6     <NA>    <NA>    SIL     <NA>    <NA>
```
Input SAD RTTM:
```
SPEAKER test2   1       0.00    2.03    <NA>    <NA>    speech  <NA>
SPEAKER test2   1       2.49    3.29    <NA>    <NA>    speech  <NA>
SPEAKER test2   1       6.45    3.5     <NA>    <NA>    speech  <NA>
SPEAKER test2   1       10.71   2.92    <NA>    <NA>    speech  <NA>
```
Yunitator Output of 'label with most duration per input segment' 
```
SPEAKER test2   1       0.00    2.03    <NA>    <NA>    SIL     <NA>
SPEAKER test2   1       2.49    3.29    <NA>    <NA>    FEM     <NA>
SPEAKER test2   1       6.45    3.5     <NA>    <NA>    FEM     <NA>
SPEAKER test2   1       10.71   2.92    <NA>    <NA>    FEM     <NA>
```
Some of this doesn't seem right. But then maybe the input SAD is not good (not gold standard). Or maybe Yunitator is just doing a terrible job. In this case, the speaker is male in all four SAD utterances: Bill Gates, who, admittedly, has a girly voice. :) 
Looking into verifying the quality of input SAD for this test input...

**Comment by fmetze** [comment]
What is the expected behavior?

1) Keep the original segmentation, and assign each input segment to a “speaker”, or
2) re-segment the input segments according to Yunitator decisions?

**Comment by riebling** [comment]
expected is 1) keep original segmentataion, assign each segment a speaker

**Comment by riebling** [comment]
![screenshot from 2018-09-26 16-33-58](https://user-images.githubusercontent.com/2487766/46107744-2e49f500-c1aa-11e8-87e3-7dabb0970d76.png)
OK for this example, SAD looks pretty golden to me

**Comment by alecristia** [comment]
Yes, this audio is cleaner than what we'll ever hope! Perhaps it was just an unlucky example, or the result of mismatching the audio quality of the training set (all LENA) with this test clip... 

Eric, could you:
1) try it on the ACLEW starter data?
2) allow the yunitator to resegment? 

Perhaps that will help us see where things go south.

**Comment by riebling** [comment]
This looks better, and shows the Yunitator bug (which we work around):
![screenshot from 2018-09-27 15-15-33](https://user-images.githubusercontent.com/2487766/46169116-35373d00-c268-11e8-892e-e1f4652c7d24.png)
Now on to testing on ACLEW Starter data....

**Comment by fmetze** [comment]
will you or Yun eventually fix the Yunitator bug?

**Comment by riebling** [comment]
Work around, for now, fix bug if Yun doesn't provide a fix first.
Meanwhile uncovered a data bug: some RTTM files have 0.00 duration segments. (ACLEW Starter data seems to be quantized to nearest whole second)
So, working around this also. Finding edge cases - good!
FIRST ACLEW STARTER DATA OUTPUT:
![screenshot from 2018-09-27 16-27-36](https://user-images.githubusercontent.com/2487766/46172774-59981700-c272-11e8-94c9-980557c53b4e.png)
![screenshot from 2018-09-27 16-26-47](https://user-images.githubusercontent.com/2487766/46172775-59981700-c272-11e8-8e44-2df61ffae47e.png)
![screenshot from 2018-09-27 16-26-34](https://user-images.githubusercontent.com/2487766/46172777-59981700-c272-11e8-8ec2-c9b321c2aefd.png)
![screenshot from 2018-09-27 16-26-22](https://user-images.githubusercontent.com/2487766/46172778-59981700-c272-11e8-8a4a-5d57fd475286.png)
![screenshot from 2018-09-27 16-26-08](https://user-images.githubusercontent.com/2487766/46172779-59981700-c272-11e8-9d3a-7882ac928b51.png)
![screenshot from 2018-09-27 16-25-49](https://user-images.githubusercontent.com/2487766/46172780-59981700-c272-11e8-9ba2-d6f27053ecd8.png)
![screenshot from 2018-09-27 16-25-26](https://user-images.githubusercontent.com/2487766/46172781-59981700-c272-11e8-9753-f2877897f3ef.png)

**Comment by riebling** [comment]
Still need to test on daylong recordings, but have a go at https://github.com/srvk/Yunitator/blob/master/runYuniSegs.sh

**Comment by alecristia** [comment]
This is excellent, thank you! Now it's on our hands here in Paris, leading to the following todo-for-completion list, all three can be done in parallel (please correct if necessary):

- [ ] Paris team runs larger test @alecristia
- [ ] Paris team fixes 0 duration starter rttms! @alecristia 
- [ ] Yun (or potentially Eric) fixes the "yunitator bug"

**Comment by jukaradayi** [comment]
@riebling "Meanwhile uncovered a data bug: some RTTM files have 0.00 duration segments. (ACLEW Starter data seems to be quantized to nearest whole second)" : 
Hmm this shouldn't happen, I'm opening an issue, I'll fix that. Thanks for uncovering it !

**Comment by riebling** [comment]
There's a 53 minute long segment in my test data that was too big for Yunitator. I guess we can add more logic to the runYuniSegs.sh script to check for big segment sizes. I was hoping the input would be more 'well formed' in that things are roughly utterance length. A 53 minute long utterance is unreasonable, but maybe not impossible, if you count politicians ;)

**Comment by riebling** [comment]
Added an option to run in such a way that if input segments are marked "SIL" they are not processed by Yunitator but rather output unchanged. This can potentially save processing time, as well as work around some inputs where huge segments get marked as silence.
https://github.com/srvk/Yunitator/blob/master/README.md#yunisegs

**Comment by alecristia** [comment]
Tool fully functional!
