### ISSUE TITLE
Yunitate crashes due to MemoryError

### ISSUE THREAD

**Issue by jaden-w** [srvk/DiViMe#43]
Traceback (most recent call last):
  File "diarize.py", line 26, in <module>
    feat = pca(readHtk(INPUT_FILE))
  File "diarize.py", line 23, in <lambda>
    pca = lambda feat: ((feat[:, mask] - mu) / sigma).dot(V) * w + b
MemoryError

I tested Yunitate at 3 different VM memory settings. These are the smallest input lengths that I tested that yunitate failed:

VM Memory (GB) | Success (min) | Fail (min)
2GB | 9 min   | 10 min
3GB | 9 min   | 10 min
4GB | 13 min | 14 min

This issue was created at the request of Prof. Metze to document the memory issue. 

edit: The data used came from the vandam3 folder here: 

https://drive.google.com/drive/u/4/folders/1Meont2RU8DbZfwmlQExEN_SiQGWft_2i

The file is e20110915_110122_007574.mp3 . The data is the first n minutes trimmed from this daylong recording.

**Comment by fmetze** [comment]
follow up in issue #44
