### ISSUE TITLE
system optimization

### ISSUE THREAD

**Issue by junghanw** [srvk/DiViMe#46]
Few observation so far,

- using miniconda instead of anaconda. (testing...)
- remove unnecessary libraries 
- minimize path manipulation inside shell scripts

**Comment by fmetze** [comment]
As we discussed, it would be great to streamline the build process, and make sure the build process is faster, and the resulting VM uses less memory. It would be great to only need to support one of Docker and Vagrant, but it seems that on Windows only "professional" and "enterprise" versions support Docker easily. We should not assume that our users have these versions. It is important for us that users can install new VMs without using Administrator rights. We should however provide both build scripts, and pre-built downloads.

**Comment by riebling** [comment]
I can speak to this as being an improvement, at a higher level. For the LENA match-up milestone, we probably want to stick with the current Vagrant provisioning and run commands, as documented in the main README and that our teams currently work with. The improvements would be potentially faster start-up, smaller size, things like that, but those are not on the critical path (nor should they be) to LENA match-up in my opinion.

**Comment by fmetze** [comment]
agree. LENA matchup has Eric on the critical path, none of the students.

**Comment by junghanw** [comment]
Closing issue as above tasks are now all completed
