### ISSUE TITLE
Evaluation : ldc_sad_hmm is missing

### ISSUE THREAD

**Issue by MarvinLavechin** [srvk/DiViMe#47]
The evaluation script **tools/eval.sh** needs the repository **ldc_sad_hmm** (https://github.com/aclew/ldc_sad_hmm). It needs to be cloned manually within the VM in /home/vagrant. 

Julien explained me that there was some copyright problems. Should we remove that from the documentation ? Or should we add the git clone in the Vagrantfile ?

**Comment by riebling** [comment]
Still waiting for LDC to give permissions so we can include it, but until then we don't officially have permission to distribute the ldc_sad_hmm code, so can't include it in the repository. This might be in another Issue, essentially: keep pestering LDC to make their tool open source, so we can include it for public use. Until then we probably need to keep cloning it manually using our 'private' copy https://github.com/aclew/ldc_sad_hmm)

**Comment by macw** [comment]
Would it help if I contacted Chris Cieri?  With whom have you been in contact on this so far?

--Brian

**Comment by alecristia** [comment]
ldc_sad and its eval have been removed
