### ISSUE TITLE
Integrate TALNet sound event classifier 

### ISSUE THREAD

**Issue by fmetze** [srvk/DiViMe#50]
Integrate Yun's best TALNet sound event classifier that can recognize 500+ categories (rather than just 17 or so)

**Comment by riebling** [comment]
Pointer to repository with this tool: https://github.com/srvk/537cls

**Comment by riebling** [comment]
Some more clarification on this might be in order; let me try to list tasks
  * some of this falls under the task to refactor all of: TALNet, Yunitator, Noisemes into one code base. I might benefit from some help from someone with better Python chops
  * write a Launcher script to call TALNet in the "DiViMe Way"
  * add TALNet to the Vagrantfile (for now this is the fastest way to get it into the VM, but will become obsolete as part of the first point)
