### ISSUE TITLE
provide analysis of annotation that is easy for newbies to read and understand

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#55]
Add scripts for visualizing and analyzing VM results, containing: 

- [x] xx.df, one per tool ran, containing performance per file
- [x] stats.txt; contains broad descriptors of activity at the file level calculated from the gold & wav (total speech, proportion of speech by children, proportion of speech that is overlapping, number of participants, number of child turns, number of child-adult turns, mean amplitude, max amplitude, snr, ... tallies of tools' added info - eg total word counts per talker and overall)
- [ ] Report.html contains plots of miss ~ false_alarm for each SAD tool, precision and recall for each diarization tool, regressions comparing different tools, regressions relating performance of different tools as a function of stats.txt regressors

**Comment by jukaradayi** [comment]
Just to clarify, the xx.df you mention are the ones currently returned by the evaluation script, right ?

**Comment by alecristia** [comment]
Yes, I think so! I wasn't sure this had been standardized. Glad to know it has!

This is a link to a file (written in Rmd) that contains code to generate both a stats.txt and a report.html: https://www.dropbox.com/s/1wk00cib9se8rcb/sltu18_ana.Rmd?dl=0
