### ISSUE TITLE
bug in rttm2labels.py

### ISSUE THREAD

**Issue by jihopark** [srvk/DiViMe#56]
I wanted to visualize the segmentation to audacity, but rttm2labels.py gives me an Exception cannot process line.

It seems like rttm output are somtimes tabbed or just spaced, so by adding
```
l = "\t".join(l.split())                                                    
```
before
```
m = re.match("^(.*)\t(.*)\t(.*)\t(\S+)\t(\S+)\t(.*)\t(.*)\t(.*)\t(.*)$", l
```
solves the problem for me.

I'm testing out your library for our company's usage (thanks for the amazing resources btw), so i'll clone this library and send a pull request

**Comment by jihopark** [comment]
i meant "fork" not clone. but do u guys accept pull requests from forked repos?

**Comment by riebling** [comment]
This would be great, thanks! Yes the assumptions about tabs vs. spaces (whitespace) in RTTM led to this. There is still a tool that does something not well formed, putting double quotes around fields in generated RTTM, within which are spaces. But maybe if a space is not a tab, and we are strict about requiring & producing tab separated values in RTTM, that's OK.

**Comment by MarvinLavechin** [comment]
I updated the script that you two are mentioning in this issue. It should be fixed now.
