### ISSUE TITLE
check for bug in LENA software evaluation

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#58]
The original LENA software outputs are .its files. Here is an example from the VanDam 5 minutes corpus on homebank:
https://www.dropbox.com/s/15dfhm80ll80dim/e20100121_152012_003985.its?dl=0

The first step involves running a script which extracts information from .its to generate a csv version, written by Anne Warlaumont and part of homebankcode:
https://github.com/HomeBankCode/lena-its-tools/blob/master/segments.pl

The second involves running this code in r:
# Periodic extraction used with the Tsimane files, where 1 minute every 60 is annotated, starting 34 mins into the recording. For other files, assume a list of on/off times may be provided

warmuptime=60*30+60*4 #initial skip 34 mins
chunklength=60*1 #code 1 min
skip=60*60 #then skip 59 mins

dir(pattern="csv")->csvs
for (j in csvs){
  all=read.csv(j)
  maxtime=all[dim(all)[1],3] #get the end of the last interval
  thistime=warmuptime
  while(thistime < maxtime){

      onset=thistime
      offset=onset + chunklength
      all[all$startsec<=offset & all$endsec>=onset,]->inc
  
  #fix edges
      if(inc[1,"startsec"] < onset) inc[1,"startsec"] <- onset
      if(inc[dim(inc)[1],"endsec"] > offset) inc[dim(inc)[1],"endsec"] <- offset
  #fix times
      inc$startsec=round(inc$startsec-thistime,2)
      inc$endsec=round(inc$endsec-thistime,2)
   chunk=gsub(".csv","",j)
    write.table(inc,paste0("extracts/",chunk,"_",onset,"_",offset,"_lena.txt"),row.names=F,quote=F,sep="\t",col.names=F)    
    thistime=thistime+skip
  }#endwhile
  }#endfor

**Comment by MarvinLavechin** [comment]
I checked and everything is functional.
I'm just not quite sure about what the three first parameters represent : 

```
warmuptime=6030+604 #initial skip 34 mins
chunklength=601 #code 1 min
skip=6060 #then skip 59 mins
```

The csv returned by the pearl script returns a time in seconds. That should be : 

```
warmuptime=2040 #initial skip 34 mins
chunklength=60 #code 1 min
skip=3540 #then skip 59 mins
```

**Comment by MarvinLavechin** [comment]
I got it !

You wanted to write 60*30 + 60 * 4 instead of 6030+604
60*1 instead of 601
and 60*59 instead of 6060

**Comment by alecristia** [comment]
no bug found so far, unclear where to look next. closing for now
