### ISSUE TITLE
dealing with long audios

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#6]
Provide tools to

- [ ] break audio into 5 minute chunks
- [ ] then concatenate the resulting 5 minute RTTMs into one big one

**Comment by fmetze** [comment]
i know we have done some work on this, but what is the status?

**Comment by riebling** [comment]
We don't have a universal way to do this yet. It's firmly on my plate.

**Comment by riebling** [comment]
See the `chunk.sh` script in http://github.com/srvk/tools/
