### ISSUE TITLE
which dataset Yunitator is trained on

### ISSUE THREAD

**Issue by jihopark** [srvk/DiViMe#62]
It would be important to specify which dataset Yunitator is trained with (or am I the only one who is missing the info?), because users can try out samples that may be included in the training dataset.

I am testing the library out with samples from Homebank (VanDam-5minutes) and found out that Yunitator works better than DiarTK. I was delighted but got suspicious whether the sample is drowned from the training set. I hope the performance comes from the fact that it is trained from other datasets with similar distribution as Homebank.

I would appreciate it if you can clarify here!

**Comment by alecristia** [comment]
Thanks, this is indeed in the todo list! #39

**Comment by riebling** [comment]
In one word, the Yunitator was trained on the "noiseme" corpus:

    S. Burger, Q. Jin, P. F. Schulam, and F. Metze, “Noisemes: manual annotation of environmental noise in audio streams”, technical report CMU-LTI-12-07, Carnegie Mellon University, 2012. 


Description of how this network was trained can be found in Section 3 of this paper:
http://www.cs.cmu.edu/~yunwang/papers/icassp16.pdf

And improvements to it can be found in Section 3.2 of this paper:
http://www.cs.cmu.edu/~yunwang/papers/icassp17.pdf

**Comment by fmetze** [comment]
Are we sure? I thought this question refers to the tool that does 4-way male/ female/ child/ silence segmentation - and this tool was *not* trained on the “noiseme” corpus. Not sure though which tool is the rightful “Yunitator”...

**Comment by jihopark** [comment]
thank you so much @alecristia. As I guessed, the sample I used for testing was in the training data, so it was performing very well.

**Comment by alecristia** [comment]
new version of the docs are up

**Comment by riebling** [comment]
Realized as soon as I posted, the training for "Yunitator" was different than "Noisemes" even though both created by Yun, they are different models and predict different classes, and Yun's answer which I copy-pasted from elsewhere was for the wrong flavour of tool.

**Comment by jihopark** [comment]
@riebling sorry if I ask too many questions.

I found out that u are doing a PCA transformation after extracting features from OpenSmile.
The weights are saved in `https://github.com/srvk/Yunitator/pca-self.pkl`.
Can you give me more details about how these weights are trained? On which dataset? Is it trained on an aggregate of all the vectors (one vector per frame) from the training audios?

**Comment by alecristia** [comment]
Here's Yun's answer:

"The PCA matrix was computed from all the training frames.
...
Yun Wang and Florian Metze, "A first attempt at polyphonic sound event detection using connectionist temporal classification", in Proceedings of the IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP), pp. 2986-2990, Mar. 2017.  "
