### ISSUE TITLE
incorporate feedback from aclew/divime

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#65]
The following may only occur if one doesn't follow the instructions:
https://github.com/aclew/DiViMe/issues/13

These ones should be addressed:
https://github.com/aclew/DiViMe/issues/12
https://github.com/aclew/DiViMe/issues/11
https://github.com/aclew/DiViMe/issues/10
https://github.com/aclew/DiViMe/issues/4

**Comment by alecristia** [comment]
@riebling these issues may be old/not relevant anymore, but could you please look into them, so we can close them here and in the ACLEW repo?

**Comment by riebling** [comment]
I've looked at them each and commented, and think we should go ahead and close, not just recommend closing in comments, as I did, so I'm going to do that now, and here as well.
