### ISSUE TITLE
building local versions of the docs

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#66]
typical instructions are to navigate inside docs, then do:

`$ make html`

However, doing so now gave me this error:

> $ make html
> Running Sphinx v1.5.6
> 
> Exception occurred:
>   File "conf.py", line 22, in <module>
> ImportError: No module named recommonmark.parser
> The full traceback has been saved in /var/folders/zl/8rc2cx7s2hx6w6c0br6x8swh0000gn/T/sphinx-err-XDfxTV.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

**Comment by riebling** [comment]
Does this happen because the `make html` command is being run on the host computer? It surely won't work on Windows, then. (or maybe that's what the .bat file is for) But maybe the VM has the programs & linux bits necessary to successfully and consistently `make html`, something like:
```
vagrant ssh -c 'cd /vagrant/docs && make html'
```

**Comment by riebling** [comment]
This looks like the Python installation in the VM (in /home/vagrant/anaconda) needs to have the recommonmark package installed. If I
```
pip install recommonmark
```
then the `make html` works from both within the VM and externally invoked, as above. As an 'immediate' fix I'll add recommonmark to the list of things installed by pip in Vagrantfile...
https://github.com/srvk/DiViMe/commit/c3554fa8cc66ae42f2028d85264b8a6ee2d1148d

**Comment by riebling** [comment]
Adding an example of output when running `make html`:
```
er1k@islpc22:/usr1/er1k/boxes/DiViMe$ vagrant ssh -c 'cd /vagrant/docs && make html'
Running Sphinx v1.3.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] index                                                 
/vagrant/docs/source/index.rst:9: WARNING: toctree contains reference to nonexisting document u'   noisemes_sad'
looking for now-outdated files... none found
pickling environment... done
checking consistency... /vagrant/docs/source/ldc_sad.md:: WARNING: document isn't included in any toctree
/vagrant/docs/source/noisemes_sad.md:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] index                                                  
generating indices... genindex
writing additional pages... search
copying static files... WARNING: html_static_path entry u'/vagrant/docs/source/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 4 warnings.

Build finished. The HTML pages are in build/html.
Connection to 127.0.0.1 closed.
```
