### ISSUE TITLE
DiViMe documentation

### ISSUE THREAD

**Issue by fmetze** [srvk/DiViMe#67]
The page at "https://github.com/srvk/DiViMe" says that this is the stable version of the ACLEW DiViMe,  and for the development version go to https://github.com/srvk/DiViMe - the same address. Which is it? 

Also, we should probably add the following references to the documentation (and encourage people to cite them if they use DiViMe):

Adrien Le Franc, Eric Riebling, Julien Karadayi, Yun Wang, Camila Scaff, Florian Metze, and Alejandrina Cristia. 
The ACLEW DiViMe: An easy-to-use diarization tool. 
In Proc. INTERSPEECH, Hyderabad; India, September 2018. ISCA.

Florian Metze, Eric Fosler-Lussier, and Rebecca Bates. 
The speech recognition virtual kitchen. 
In Proc. INTERSPEECH, Lyon; France, August 2013. ISCA. 
https://github.org/srvk.

**Comment by alecristia** [comment]
implemented, will be visible when we merge branch major_reorganization with main
