### ISSUE TITLE
hide visibility of e.g. environment.yml, update.sh, bootstrap.sh?

### ISSUE THREAD

**Issue by riebling** [srvk/DiViMe#78]
Would it be possible to install from /vagrant/conf/environment.yml directly, thus keeping it out of the /home/vagrant folder (for those intrepid enough to go looking)

Same idea could also work for bootstrap.sh (but maybe we want to keep that more high level and visible).

Same for update.sh

General idea being: hide anything obvious and visible that someone might try and run, or that does not need to be in top level folders.

**Comment by junghanw** [comment]
#82
