### ISSUE TITLE
Strange output at end of 'vagrant up'

### ISSUE THREAD

**Issue by riebling** [srvk/DiViMe#81]
We are seeing some bizarre looking output from `update.sh` being run at the end of Vagrantfile.
Some of it we can just suppress. Others looks like repository skew:
```
    default: You are not currently on a branch. Please specify which
    default: branch you want to merge with. See git-pull(1) for details.
    default: 
    default:     git pull <remote> <branch>
    default: HEAD is now at b3e4deb... don't exit early; process every RTTM line
    default: Already up-to-date.
    default: Already up-to-date.
    default: Already up-to-date.
    default: You are not currently on a branch. Please specify which
    default: branch you want to merge with. See git-pull(1) for details.
    default: 
    default:     git pull <remote> <branch>
    default: HEAD is now at 70196a8... fix arguments
```

**Comment by riebling** [comment]
Maybe some of this will look better for the final public version which will not pull from the head, but rather from a Tagged Release. 
In fact: This is why the strange output, I think: `bootstrap.sh` gets headless versioned repos with syntax like this:
```
git clone https://github.com/srvk/To-Combo-SAD --branch v1.0
```
so subsequently doing `git pull` on these abnormal clones gives the complaints

**Comment by junghanw** [comment]
To make it simpler for tagging and maintaining repositories, we use master branch for each tools as a release branch, and we make changes on develop branches and merge it back to master branch for new releases. We can tag releases directly on master branch. 

When we want to force users to use certain release, this information should go into provision step as 
``` 
git checkout [release_tag]
```

This would prevent detached head problem.
