### ISSUE TITLE
very long warning remote connection: solution by just waiting

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#9]
I installed divime in a macbook air running high sierra 10.13. After the first vagrant up to set up, the second vagrant up (to actually use the machine) led to a very long list of warnings (see below). It eventually ended, but creating an issue in case others encounter the same behavior and become worried about it. It looks like one just needs to wait.

> ==> default: Forwarding ports...
>     default: 22 (guest) => 2200 (host) (adapter 1)
> ==> default: Running 'pre-boot' VM customizations...
> ==> default: Booting VM...
> ==> default: Waiting for machine to boot. This may take a few minutes...
>     default: SSH address: 127.0.0.1:2200
>     default: SSH username: vagrant
>     default: SSH auth method: private key
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection reset. Retrying...
> ==> default: Machine booted and ready!

**Comment by riebling** [comment]
confirmed as a known behavior that happens unpredictably; the wait is ~5 minutes
