### ISSUE TITLE
sphinx missing?

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#90]
Upon vagrant up, the call `cd /vagrant/docs && make html` yields:

> ==> default: /bin/sh: sphinx-build: command not found
> ==> default: make: 
> ==> default: *** [html] Error 127

After building, `$ vagrant ssh -c 'cd /vagrant/docs && make html'`yields

> /bin/sh: /home/vagrant/anaconda/bin/sphinx-build: /home/vagrant/anaconda/bin/python: bad interpreter: No such file or directory
> make: *** [html] Error 126
>

**Comment by junghanw** [comment]
199d5b3e4bde8927460b01c86c1c9c00e059d012
During vagrant provisioning, we have to use absolute path for anaconda.

**Comment by riebling** [comment]
Closing this because it works now in the major_reorganization branch:
```
er1k@islpc22:~/boxes/major_reorganization/DiViMe$ vagrant ssh -c 'cd /vagrant/docs && make html'
Running Sphinx v1.3.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
no targets are out of date.
build succeeded.

Build finished. The HTML pages are in build/html.
Connection to 127.0.0.1 closed.
```
