### ISSUE TITLE
adapting VM features locally: macbook air 11"

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#91]
1.6 gHz intel core (dual)
4GB 1600 MHz DDR3

installation freezes and computer may reboot with the usual VM specs, namely:

>     vbox.cpus = 2
>     vbox.memory = 3072

Installation freezes but computer is intolerably slow with:

>     vbox.cpus = 2
>     vbox.memory = 2048

All seems okay with:

>     vbox.cpus = 1
>     vbox.memory = 1024

**Comment by riebling** [comment]
Very interesting; I didn't think some of the tools would work with less than 2GB of virtualized memory. Maybe that was tools we've since eliminated (LDC)?

**Comment by alecristia** [comment]
With 1024, the VM is not functional: 

> $ vagrant ssh -c "launcher/test.sh"
> Starting tests
> Checking for HTK...
> HTK is installed.
> Testing noisemes...
>    Noisemes failed - dependencies
>    Noisemes failed - no RTTM output
> Testing OpenSmile SAD...
> OpenSmile SAD passed the test.
> Testing ToCombo SAD...
> TOCOMBO SAD passed the test.
> Testing DIARTK...
> DiarTK passed the test.
> Testing Yunitator...
>    Yunitator failed - dependencies
> TEST DIR
> /vagrant/data/VanDam-Daylong/BN32/test/yunitator-test.log
>    Yunitator failed - no output RTTM
> Testing the evaluation pipeline...
> launcher/test.sh: line 163: activate: No such file or directory
> rm: cannot remove ‘/vagrant/data/VanDam-Daylong/BN32/test/accuracy_noisemesSad_report.csv’: No such file or directory
> /home/vagrant/launcher/eval.sh: line 82: activate: No such file or directory
> Traceback (most recent call last):
>   File "/home/vagrant/utils/compute_metrics.py", line 1, in <module>
>     from pyannote.core import Segment, Timeline, Annotation
> ImportError: No module named pyannote.core
> /home/vagrant/launcher/eval.sh: line 94: conda: command not found
>    The evaluation pipeline failed - dependencies
>    The evaluation pipeline failed the test - output does not match expected
> launcher/test.sh: line 172: conda: command not found
> Testing VCM...
>    VCM failed - no output RTTM
> Testing WCE...
> Error using LSTMseg (line 132)
> LSTM segmentation Python call failed. Aborting.
> 
> Error in getSyllables (line 57)
> 
> 
> Error in WCEtrain (line 151)
> 
> 
>    WCE failed - dependencies
> WCE failed - no successful adaptation
> Some tools did not pass the test, but you can still use others
> ######################################################################################
> To wrap up, we will print out the results of the analyses that we ran during the test.
> Compare the following results, corresponding to your system, against the reference results printed out below.
> If the numbers are similar, then your system is working similarly to the original one.
> If you see bigger changes, then please paste this output onto an issue on https://github.com/srvk/DiViMe/issues/.
> RESULTS:
> LINES: 10	DURATION SUM: 296.23	FILE: /vagrant/data/VanDam-Daylong/BN32/test/diartk_goldSad_BN32_010007_test.rttm
> LINES: 88	DURATION SUM: 212.22	FILE: /vagrant/data/VanDam-Daylong/BN32/test/opensmileSad_BN32_010007_test.rttm
> LINES: 56	DURATION SUM: 63.66	FILE: /vagrant/data/VanDam-Daylong/BN32/test/tocomboSad_BN32_010007_test.rttm
> LINES: 0	DURATION SUM: 	FILE: /vagrant/data/VanDam-Daylong/BN32/test/tocomboSad_*.ToCombo.txt.rttm
> ****** REFERENCE RESULTS BEGINS ******.
> LINES: 101	DURATION SUM: 298.637	FILE: /vagrant/data/VanDam-Daylong/BN32/test/BN32_010007_test.rttm
> LINES: 101	DURATION SUM: 298.637	FILE: /vagrant/data/VanDam-Daylong/BN32/test/diartk_goldSad_BN32_010007_test.rttm
> LINES: 37	DURATION SUM: 31.9	FILE: /vagrant/data/VanDam-Daylong/BN32/test/noisemesSad_BN32_010007_test.rttm
> LINES: 88	DURATION SUM: 212.22	FILE: /vagrant/data/VanDam-Daylong/BN32/test/opensmileSad_BN32_010007_test.rttm
> LINES: 56	DURATION SUM: 63.66	FILE: /vagrant/data/VanDam-Daylong/BN32/test/tocomboSad_BN32_010007_test.rttm
> LINES: 31	DURATION SUM: 24.7	FILE: /vagrant/data/VanDam-Daylong/BN32/test/vcm_BN32_010007_test.rttm
> LINES: 105	DURATION SUM: 302	FILE: /vagrant/data/VanDam-Daylong/BN32/test/yunitator_BN32_010007_test.rttm
> ****** REFERENCE RESULTS ENDS ******.
> Evaluation pipeline:
> 
> Evaluating noisemesSad on /vagrant/data/VanDam-Daylong/BN32/test with respect to : accuracy
> 
> accuracy report
>                       detection accuracy true positive true negative false positive false 
>                                        %                                                  
> item                                                                                      
> BN32_010007_test.rttm              11.24         30.80          3.11           0.20         267.57
> TOTAL                              11.24         30.80          3.11           0.20         267.57
> Connection to 127.0.0.1 closed.
>

**Comment by alecristia** [comment]
macbook 11" 1.6 gHz intel core (dual)
4GB 1600 MHz DDR3
crashes when
vbox.cpus = 1
vbox.memory = 2048

If the hypothesis that errors in the log above are due to space constraints, then this means we need to specify a much bigger minimum RAM in the instructions.

**Comment by alecristia** [comment]
@fmetze, do you think we should update the installation instructions, to up the minimal requirements as described in this issue?

**Comment by fmetze** [comment]
Again, I have updated the documentation itself (see https://github.com/srvk/DiViMe/blob/master/docs/source/install.md), but we need to understand how this information gets propagated to https://divime.readthedocs.io/en/latest/install.html
