### ISSUE TITLE
test results new install: missing numpy?

### ISSUE THREAD

**Issue by alecristia** [srvk/DiViMe#92]
Full test results below. DScore fails because it's in the process of being added. Not sure why VCM fails -- perhaps integration is not complete?

> $ vagrant ssh -c 'test.sh'
> Starting tests
> Checking for HTK...
> HTK is installed.
> Testing noisemes...
>    Noisemes failed - no RTTM output
> Testing OpenSmile SAD...
> OpenSmile SAD passed the test.
> Testing ToCombo SAD...
> TOCOMBO SAD passed the test.
> Testing DIARTK...
>    Diartk failed - no output RTTM
> Testing Yunitator...
>    Yunitator failed - no output RTTM
> Testing Dscore...
> **Traceback (most recent call last):
>   File "score_batch.py", line 73, in <module>
>     from scorelib.score import score
>   File "/home/vagrant/repos/dscore/scorelib/score.py", line 8, in <module>
>     import numpy as np
> ImportError: No module named numpy**
>    Dscore failed - dependencies
>    DScore failed the test - output does not match expected
> Testing VCM...
>    **VCM failed - no output RTTM**
> Some tools did not pass the test, but you can still use others
> RESULTS:
> LINES: 101	DURATION SUM: 298.637	FILE: /vagrant/data/VanDam-Daylong/BN32/test/BN32_010007_test.rttm
> LINES: 0	DURATION SUM: 	FILE: /vagrant/data/VanDam-Daylong/BN32/test/diartk_goldSad_BN32_010007_test.rttm
> LINES: 88	DURATION SUM: 212.22	FILE: /vagrant/data/VanDam-Daylong/BN32/test/opensmileSad_BN32_010007_test.rttm
> LINES: 56	DURATION SUM: 63.66	FILE: /vagrant/data/VanDam-Daylong/BN32/test/tocomboSad_BN32_010007_test.rttm
> LINES: 0	DURATION SUM: 	FILE: /vagrant/data/VanDam-Daylong/BN32/test/yunitator_BN32_010007_test.rttm
> DSCORE:
> cat: /vagrant/data/VanDam-Daylong/BN32/test/test.df: No such file or directory

**Comment by junghanw** [comment]
I just rebuilt the VM and ran test.sh and VM passes all the tests. Is there other commands that you ran before running the test script?

**Comment by MilesICL** [comment]
@alecristia did you run the latest version with branch major_reorganization? VCM seems working well in my env.

**Comment by junghanw** [comment]
I see there's OSError: [Errno 12] Cannot allocate memory. I'll try it with 1GB memory with my laptop.

**Comment by junghanw** [comment]
I also got same error with 1GB memory. I'll try if miniconda works in such case. Otherwise, we should come up with minimum requirement for VM?

**Comment by junghanw** [comment]
I ran into same error even with miniconda. 
```
Traceback (most recent call last):
    default:       File "/home/vagrant/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 819, in __call__
    default:         return func(*args, **kwargs)
    default:       File "/home/vagrant/anaconda/lib/python2.7/site-packages/conda_env/cli/main.py", line 74, in do_call
    default:         exit_code = getattr(module, func_name)(args, parser)
    default:       File "/home/vagrant/anaconda/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 108, in execute
    default:         installer.install(prefix, pkg_specs, args, env)
    default:       File "/home/vagrant/anaconda/lib/python2.7/site-packages/conda_env/installers/pip.py", line 40, in _pip_install_via_requirements
    default:         args, pip_version = pip_args(prefix)
    default:       File "/home/vagrant/anaconda/lib/python2.7/site-packages/conda_env/pip_util.py", line 33, in pip_args
    default:         pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
    default:       File "/home/vagrant/anaconda/lib/python2.7/subprocess.py", line 216, in check_output
    default:         process = Popen(stdout=PIPE, *popenargs, **kwargs)
    default:       File "/home/vagrant/anaconda/lib/python2.7/subprocess.py", line 394, in __init__
    default:         errread, errwrite)
    default:       File "/home/vagrant/anaconda/lib/python2.7/subprocess.py", line 938, in _execute_child
    default:         self.pid = os.fork()
    default:     OSError: [Errno 12] Cannot allocate memory
```

**Comment by alecristia** [comment]
did you try it with 2GB? 

I'd vote then to set a minimum and just tell users with poor computers that things won't work.

**Comment by junghanw** [comment]
2 core and 2GB works.

**Comment by riebling** [comment]
Confirm all working at 1 core + 2GB, which should probably be our minimum configuration.
